
;-----------------------------------------------------------------------
; BIOS for TimmiOS - The SAL-16 Operating System
;
; It does the following:
;
; a) Jumps to the start of the program in RAM at start up.
;
; b) An Interrupt Vector Table is at 0x0010 & allows for 3 interrupts,
;    generated by the ENTER_1 & ENTER_2 buttons plus the keyboard, with
;    Interrupt Services Routines located at 0xb000, 0xb100 & 0xb200.
;
; c) Contains the BIOS routines.
;-----------------------------------------------------------------------

;---------------------------------------------
; Defines for use in programs using the BIOS:
;
; .equ os_get_in      0x1000
; .equ os_disp_out    0x1030
; .equ os_read_char   0x1050
; .equ os_print_char  0x1080
; .equ os_read_str    0x10a0
; .equ os_print_str   0x10e0
; .equ os_mem_set     0x1110
; .equ os_mem_setn    0x1130
; .equ os_mem_read    0x1150
; .equ os_read_int    0x1170
; .equ os_print_int   0x11d0
; .equ os_read_uint   0x1230
; .equ os_print_uint  0x1280
; .equ os_read_float  0x1330
; .equ os_print_float 0x16b0
; .equ os_exit        0x1a90
; .equ os_play_tune   0x1ac0
; .equ os_delay       0x1af0
;
; .equ IN_1  3
; .equ IN_2  7
; .equ OUT_1 6
; .equ OUT_2 10
;---------------------------------------------

.ROM

; Memory Map
.equ PROG_START 0x8000
.equ HEAP_SIZE  0xc000
.equ HEAP_END   0xc001
.equ HEAP_START 0xc002
.equ IO_START   0xfff0

; Interrupts
.equ INT_ENT_1 0xb000
.equ INT_ENT_2 0xb100
.equ INT_KBD   0xb200

; IO Devices
.equ ERR 0xfff0
.equ KBD 0xfff1
.equ TTY 0xfff2
.equ SND 0xfffb

.equ IN_1  3
.equ IN_2  7
.equ OUT_1 6
.equ OUT_2 10

; ASCII Chars
.equ CHR_ENT   0x0a
.equ CHR_MINUS 0x2d
.equ CHR_ZERO  0x30

; Error Codes
.equ DIV_BY_0     0x0100
.equ POW_UNDEF    0x0110
.equ BAD_INT      0x0120
.equ INV_DATA     0x0130
.equ BAD_VEC_DIMS 0x0140
.equ BAD_MAT_DIMS 0x0150
.equ LN_LTE_ZERO  0x0160

; Stack Pointer Violation
.equ SP_ERR 0x0e00

; SAL-16I Error Code
.equ NO_FPU 0x0f00

; Misc
.equ TRUE  1
.equ FALSE 0

.equ GET_INT_NUM 4         ; To show up to 5 digits when displayed integers on the text screen
.equ MAX_SIGN_INT 0x7fff   ; The maximum signed integer

.code

;-------------------------------------------------------------
; Set the end of the heap in the stack pointer circuitry
;-------------------------------------------------------------

bios_start:
   mov HEAP_SIZE,r0
   mov [r0],r1             ; r1 = 'heap size'

   clr r2                  ; 'heap size' = 0 ?
   cmp r1,r2
   jeq no_heap

   mov HEAP_START,r2
   add r2,r1,r1            ; r1 = End of the heap = HEAP_START + 'heap size' - 1
   dec r1
   jmp set_heap_end

no_heap:
   mov HEAP_END,r1         ; No heap, but don't allow the stack ptr to reach addr HEAP_END

set_heap_end:
   mov HEAP_END,r0         ; Mem(HEAP_END) = Addr of the end of the heap 
   mov r1,[r0]
   endhp [r0]

;-------------------------------
; Goto the start of the program
;-------------------------------

   jmp PROG_START

;------------------------
; Interrupt Vector Table
;------------------------

.= 0x00f0
   jmp INT_ENT_1
   jmp INT_ENT_2
   jmp INT_KBD
   jmp SP_ERR
   jmp NO_FPU              ; Only for SAL-16I

;----------------
; Error Handling
;----------------

; Display error code on OUT_1, turn on ERR LED & stop

; Division by 0
.= 0x0100
   mov DIV_BY_0,r0
   jmp os_exit

; Undefined power: 0^0
.= 0x0110
   mov POW_UNDEF,r0
   jmp os_exit

; Integer not in range
.= 0x0120
   mov BAD_INT,r0
   jmp os_exit

; Invalid input data
.= 0x0130
   mov INV_DATA,r0
   jmp os_exit

; Bad vector dimensions
.= 0x0140
   mov BAD_VEC_DIMS,r0
   jmp os_exit

; Bad matrix dimensions
.= 0x0150
   mov BAD_MAT_DIMS,r0
   jmp os_exit

; ln(x) with x <= 0.0
.= 0x0160
   mov LN_LTE_ZERO,r0
   jmp os_exit

; Stack Pointer Violation
.= 0x0e00
   mov SP_ERR,r0
   jmp os_exit

; No FPU available for floating point instructions (only used by SAL-16I)
.= 0x0f00
   mov NO_FPU,r0
   jmp os_exit

;------------------------------------------------
; BIOS - Get a word from IN_1 or IN_2
;
; Location: ROM addr 0x1000
;
; Input  - R0 = Device ID: 3 (IN_1) or 7 (IN_2)
; Output - R0 = Entered word
;------------------------------------------------

.= 0x1000

os_get_in:
   push r3              ; Save used registers
   push r2
   push r1

   clr r1               ; r1 = 0
   clr r2               ; r2 = 0
   mov IO_START,r3      ; r3 = 0xfff0 (the start of I/O memory)
   add r0,r3,r3         ; r3 now points to IN_x

   add r3,r1,r1
   inc r1               ; r1 points to WAIT_x (the 'waiting' LED)

   add r1,r2,r2         ; r2 points to ENTER_x (the enter button)
   inc r2

   mov 1,r0             ; Turn the LED on
   mov r0,[r1]
   push r1              ; Store the WAIT_x addr on the stack

in_chk_ent:
   mov [r2],r1          ; Put the button state in r1
   cmp r0,r1
   jgt in_chk_ent       ; Stay in the 'check_enter loop' until the button is pressed

   pop r1               ; Retrieve the WAIT_x addr from the stack
   clr r0
   mov r0,[r1]          ; Turn off the LED
   mov [r3],r0          ; r0 = IN_x

   pop r1               ; Retrieve registers
   pop r2
   pop r3
   ret

;-------------------------------------------------
; BIOS - Display a word on OUT_1 or OUT_2
;
; Location: ROM addr 0x1030
;
; Input - R0 = Device ID: 6 (OUT_1) or 10 (OUT_2)
;         R1 = Value to be displayed
;-------------------------------------------------

.= 0x1030

os_disp_out:
   push r2              ; Save used register

   mov IO_START,r2      ; r2 holds the device addr
   add r2,r0,r0
   mov r1,[r0]          ; Store display val to device addr

   pop r2               ; Retrieve register
   ret

;-------------------------------------------
; BIOS - Read a character from the keyboard
;
; Location: ROM addr 0x1050
;
; Output - R0 = The character read
;-------------------------------------------

.= 0x1050

os_read_char:
   push r3              ; Save used registers
   push r2
   push r1

   mov KBD,r2
   mov TTY,r3
   clr r1               ; r1 is used to test for an available char

gc_rd_val:
   mov [r2],r0          ; Read a char from the keyboard
   cmp r0,r1            ; Got a char ?
   jeq gc_rd_val        ; No char - try another read     

   mov r0,[r3]          ; Display the char

   pop r1               ; Retrieve registers
   pop r2
   pop r3
   ret

;--------------------------------------------
; BIOS - Print a character on the display
;
; Location: ROM addr 0x1080
;
; Input - R0 = The character to be displayed
;--------------------------------------------

.= 0x1080

os_print_char:
   push r1              ; Save used register

   mov TTY,r1
   mov r0,[r1]          ; Display the char

   pop r1               ; Retrieve register
   ret

;-----------------------------------------
; BIOS - Read a string from the keyboard
;
; Location: ROM addr 0x10a0
;
; Input - R0 = Address of the string read
;-----------------------------------------

.= 0x10a0

os_read_str:
   push fp             ; Save used registers
   push idx
   push r4
   push r3
   push r2
   push r1
   push r0

   mov r0,r1
   mov 0x0a,r2          ; 'LF'
   mov TTY,r3
   mov KBD,r4
   clr idx
   clr fp               ; fp is used to test for an available char

gs_next:
   mov [r4],r0          ; Read a char from the keyboard
   cmp r0,fp            ; Got a char ?
   jeq gs_next          ; No char - try another read     

   cmp r0,r2            ; We're done if it's a LF
   jeq gs_done
   mov r0,[r3]          ; Display the char
   mov r0,[r1,idx]      ; Store the char
   inc idx
   jmp gs_next

gs_done:
   clr r2
   mov r2,[r1,idx]      ; Store null (string terminator)

   pop r0               ; Retrieve registers
   pop r1
   pop r2
   pop r3
   pop r4
   pop idx
   pop fp
   ret

;--------------------------------------------------------
; BIOS - Print a string on the display
;
; Location: ROM addr 0x10e0
;
; Input - R0 = The address of the string to be displayed
;--------------------------------------------------------

.= 0x10e0

os_print_str:
   push idx             ; Save used registers
   push r3
   push r2
   push r1

   mov TTY,r1
   clr idx
   clr r3               ; r3 is used to test for null (end of string)

ps_next:
   mov [r0,idx],r2      ; Get the next char from memory
   cmp r2,r3            ; If it's a null we're done
   jeq ps_done
   mov r2,[r1]          ; Print the char
   inc idx
   jmp ps_next

ps_done:
   pop r1               ; Retrieve registers
   pop r2
   pop r3
   pop idx
   ret

;---------------------------
; BIOS - Memory Set
;
; Location: ROM addr 0x1110
;
; Inputs: R0 = address
;         R1 = value
;---------------------------

.= 0x1110

os_mem_set:
	mov r1,[r0]          ; Store value to address
   ret

;-------------------------------
; BIOS - Memory Region Set
;
; Location: ROM addr 0x1130
;
; Inputs: R0 = starting address
;         R1 = number of bytes
;         R2 = value
;-------------------------------

.= 0x1130

os_mem_setn:
   push idx             ; Save used register

   clr idx

ms_loop:
   cmp idx,r1           ; Done the whole region ?
   jeq ms_done
	mov r2,[r0,idx]      ; Store value to address
   inc idx
   jmp ms_loop

ms_done:
   pop idx              ; Retrieve register
   ret

;---------------------------
; BIOS - Memory Read
;
; Location: ROM addr 0x1150
;
; Inputs: R0 = address
; Output: R0 = value
;---------------------------

.= 0x1150

os_mem_read:
   push r1              ; Save used register

	mov [r0],r1	         ; Read value at address
	mov r1,r0	         ; Return value

   pop r1               ; Retrieve register
   ret

;------------------------------------------------
; BIOS - Read a signed integer from the keyboard
;
; Location: ROM addr 0x1170
;
; Output - R0 = The signed integer read
;------------------------------------------------

.= 0x1170

os_read_int:
   push lr              ; Save used registers
   push fp
   push idx
   push r4
   push r3
   push r2
   push r1

   clr r2               ; number (r2) = 0
   mov FALSE,r4         ; Clear 'minus flag' (r4)
   clr idx              ; char count (idx) = 0
   mov 10,r1            ; r1 is used to store 10 for digit multiplication & to test digit limit

gi_next_char:
   mov KBD,fp           ; Read a char from the keyboard
   mov [fp],r0
   clr lr               ; Got a char ?
   cmp r0,lr
   jeq gi_next_char     ; No char - try another read     

   inc idx              ; char count += 1

   mov CHR_ENT,r3       ; Is it the 'Enter' key ? 
   cmp r0,r3
   jeq gi_done

   mov TTY,fp           ; Display char on text screen
   mov r0,[fp]

   mov CHR_MINUS,r3     ; Is it the '-' key ? 
   cmp r0,r3
   jne gi_read_next
   mov 1,lr             ; '-' only allowed as the 1st char
   cmp idx,lr
   jne gi_bad_char
   mov TRUE,r4          ; Set 'minus' flag
   jmp gi_next_char

gi_read_next:
   mov CHR_ZERO,r3      ; r0 is the next digit (char - CHR_ZERO)
   sub r0,r3,r0
   jmi gi_bad_char      ; digit < 0 ? - If so it's invalid
   cmp r0,r1            ; digit > 9 ? - If so it's invalid
   jge gi_bad_char

   mul r2,r1,r2         ; Update the number with the digit 
   add r2,r0,r2

   mov MAX_SIGN_INT,r3  ; Check it's a valid number (-32,767 -> 32,767)
   cmp r2,r3
   jle gi_next_char

	jmp BAD_INT          ; The number's out of range

gi_done:
   mov FALSE,lr
   cmp r4,lr            ; Is it a negative number ?
   jeq gi_pos
   not r2,r2            ; Negate number
   inc r2

gi_pos:
   mov r2,r0            ; r0 = number
   pop r1               ; Restore registers & return
   pop r2
   pop r3
   pop r4
   pop idx
   pop fp
   pop lr
	ret

gi_bad_char:
   clr r2               ; Just set number = 0 on an invalid char
   jmp gi_done

;-------------------------------------------------
; BIOS - Print a signed integer on the display
;
; Location: ROM addr 0x11d0
;
; Input - R0 = The signed integer to be displayed
;-------------------------------------------------

.= 0x11d0

os_print_int:
   push lr              ; Save used registers
   push fp
   push idx
   push r4
   push r3
   push r2
   push r1
   push r0

   mov TTY,r4           ; r4 = Display address
   mov CHR_ZERO,fp      ; fp = ASCII '0'

   clr r1               ; Determine if number < 0, = 0 or > 0 ?
   add r0,r1,r0
   jeq pi_zero
   jpl pi_pos

   mov CHR_MINUS,r1     ; Display '-'
   mov r1,[r4]
   not r0,r0            ; r0 = abs(number)
   inc r0

pi_pos:
   mov GET_INT_NUM,idx  ; Initialise digit count
   mov 10,r2            ; Divisor (r2) = 10
   mov TRUE,r3          ; Set 'leading zero' flag

pi_next_dig:
   udiv r0,r2,r1        ; Remainder (r1) is the next decimal digit - this is doing: r1 = r0 % r2
   mul r1,r2,r1
   sub r0,r1,r1

   add r1,fp,r1         ; r1 = ASCII value for the digit
   push r1              ; Save the digit char on the stack
   udiv r0,r2,r0        ; Divide r0 by 10
   dec idx
   jmi pi_disp          ; Done all digits ?
   jmp pi_next_dig

pi_disp:                ; Display the decimal digits 
   mov GET_INT_NUM,idx
   mov TRUE,lr

pi_next_char:
   pop r0   	         ; Get the next char

   cmp r0,fp            ; Is the char a leading zero ?
   jne pi_disp_char
   cmp r3,lr
   jeq pi_lead_zero     ; Don't display leading zeros

pi_disp_char:
   mov FALSE,r3         ; Clear 'leading zero' flag
   mov r0,[r4]          ; Display the char

pi_lead_zero:
   dec idx
   jmi pi_done          ; Displayed all chars ?
   jmp pi_next_char

pi_zero:
   mov CHR_ZERO,r0      ; Display '0'
   mov r0,[r4]
   
pi_done:
   pop r0               ; Restore registers & return
   pop r1
   pop r2
   pop r3
   pop r4
   pop idx
   pop fp
   pop lr
   ret

;---------------------------------------------------
; BIOS - Read an unsigned integer from the keyboard
;
; Location: ROM addr 0x1230
;
; Output - R0 = The unsigned integer read
;---------------------------------------------------

.= 0x1230

os_read_uint:
   push lr              ; Save used registers
   push fp
   push idx
   push r4
   push r3
   push r2
   push r1

   clr r2               ; number (r2) = 0
   mov 10,r1            ; r1 is used to store 10 for digit multiplication & to test digit limit
   mov CHR_ENT,r3
   mov CHR_ZERO,r4
   mov KBD,idx
   mov TTY,fp
   clr lr               ; lr is used for char detection

gu_next_char:
   mov [idx],r0         ; Read a char from the keyboard
   cmp r0,lr            ; Got a char ?
   jeq gu_next_char     ; No char - try another read     

   cmp r0,r3            ; Is it the 'Enter' key ? 
   jeq gu_done

   mov r0,[fp]          ; Display char on text screen

   sub r0,r4,r0         ; r0 is the next digit (char - CHR_ZERO)
   jmi gu_err           ; digit < 0 ? - If so it's invalid
   cmp r0,r1            ; digit > 9 ? - If so it's invalid
   jge gu_err

   mul r2,r1,r2         ; Update the number with the digit
   jc gu_err            ; Checking it's not out of range
   add r2,r0,r2
   jc gu_err

   jmp gu_next_char

gu_err:
	jmp BAD_INT          ; An invalid char or the number's out of range

gu_done:
   mov r2,r0            ; r0 = number
   pop r1               ; Restore registers & return
   pop r2
   pop r3
   pop r4
   pop idx
   pop fp
   pop lr
	ret

;---------------------------------------------------
; BIOS - Print an unsigned integer on the display
;
; Location: ROM addr 0x1280
;
; Input - R0 = The unsigned integer to be displayed
;---------------------------------------------------

.= 0x1280

os_print_uint:
   push lr              ; Save used registers
   push fp
   push idx
   push r4
   push r3
   push r2
   push r1
   push r0

   mov TTY,r4           ; r4 = Display address

   clr r1               ; Is number = 0 ?
   add r0,r1,r0
   jeq pu_zero

   mov GET_INT_NUM,idx  ; Initialise digit count
   mov CHR_ZERO,fp      ; fp = ASCII '0'
   mov 10,r2

pu_next_dig:
   udiv r0,r2,r1        ; Remainder (r1) is the next decimal digit - this is doing: r1 = r0 % r2
   mul r1,r2,r1
   sub r0,r1,r1

   add r1,fp,r1         ; r1 = ASCII value for the digit
   push r1              ; Save the digit char on the stack
   udiv r0,r2,r0        ; Divide r0 by 10
   dec idx
   jmi pu_disp          ; Done all digits ?
   jmp pu_next_dig

pu_disp:                ; Display the decimal digits
   mov GET_INT_NUM,idx  ; Initialise digit count
   mov TRUE,r3          ; Set 'leading zero' flag
   mov TRUE,lr          

pu_next_char:
   pop r0   	         ; Get the next char

   cmp r0,fp            ; Is the char a leading zero ?
   jne pu_disp_char
   cmp r3,lr
   jeq pu_lead_zero     ; Don't display leading zeros

pu_disp_char:
   mov FALSE,r3         ; Clear 'leading zero' flag
   mov r0,[r4]          ; Display the char

pu_lead_zero:
   dec idx
   jmi pu_done          ; Displayed all chars ?
   jmp pu_next_char

pu_zero:
   mov CHR_ZERO,r0      ; Display '0'
   mov r0,[r4]
   
pu_done:
   pop r0               ; Restore registers & return
   pop r1
   pop r2
   pop r3
   pop r4
   pop idx
   pop fp
   pop lr
   ret

;-----------------------------------------------
; BIOS - Convert an 'int' digit to a 'float'
;
; This is a helper function for 'os_read_float'
;
; Location: ROM addr 0x12d0
;
; Input  - R0 = The 'int' digit to be converted
; Output - R0 = The resulting 'float' digit
;
; See 'OS_BIOS.rmg'
;-----------------------------------------------

.= 0x12d0

int_dig_to_flt:
   push r1              ; Save used register
   mov 9,r1             ; Is val = 9 ?
   cmp r0,r1
   jne idtf_test_8
   mov 9.0,r0           ; Return 9.0
   jmp idtf_done
idtf_test_8:
   dec r1               ; Is val = 8 ?
   cmp r0,r1
   jne idtf_test_7
   mov 8.0,r0           ; Return 8.0
   jmp idtf_done
idtf_test_7:
   dec r1               ; Is val = 7 ?
   cmp r0,r1
   jne idtf_test_6
   mov 7.0,r0           ; Return 7.0
   jmp idtf_done
idtf_test_6:
   dec r1               ; Is val = 6 ?
   cmp r0,r1
   jne idtf_test_5
   mov 6.0,r0           ; Return 6.0
   jmp idtf_done
idtf_test_5:
   dec r1               ; Is val = 5 ?
   cmp r0,r1
   jne idtf_test_4
   mov 5.0,r0           ; Return 5.0
   jmp idtf_done
idtf_test_4:
   dec r1               ; Is val = 4 ?
   cmp r0,r1
   jne idtf_test_3
   mov 4.0,r0           ; Return 4.0
   jmp idtf_done
idtf_test_3:
   dec r1               ; Is val = 3 ?
   cmp r0,r1
   jne idtf_test_2
   mov 3.0,r0           ; Return 3.0
   jmp idtf_done
idtf_test_2:
   dec r1               ; Is val = 2 ?
   cmp r0,r1
   jne idtf_test_1
   mov 2.0,r0           ; Return 2.0
   jmp idtf_done
idtf_test_1:
   dec r1               ; Is val = 1 ?
   cmp r0,r1
   jne idtf_zero
   mov 1.0,r0           ; Return 1.0
   jmp idtf_done
idtf_zero:
   clr r0               ; Return 0.0
idtf_done:
   pop r1               ; Restore register
   ret

;------------------------------------------------
; BIOS - Read a 'float' number from the keyboard
;
; Location: ROM addr 0x1330
;
; Output - R0 = The 'float' number
;
; NB: This code is taken from the auto-generated
;     code produced by compiling 'OS_BIOS.rmg'
;------------------------------------------------

.= 0x1330

os_read_float:
   push r1     ; Save registers
   push r2
   push r3
   push r4
   push idx
   push lr     ; Auto-generated code
   push fp
   movsp fp
   clr r0
   push r0
   clr r0
   push r0
   clr r0
   push r0
   clr r0
   push r0
   clr r0
   push r0
   clr r0
   push r0
   clr r0
   push r0
   clr r0
   push r0
   clr r0
   push r0
   mov 18688,r0
   push r0
   clr r0
   push r0
   clr r0
   push r0
   mov -10,idx
   add fp,idx,r0
   mov -11,idx
   mov r0,[fp,idx]
   mov -11,idx
   mov [fp,idx],r0
   mov 32256,r1
   call os_mem_set
   call os_read_char
   clr idx
   mov r0,[fp,idx]
   clr idx
   mov [fp,idx],r0
   push r0
   mov 45,r0
   push r0
   pop r1
   pop r0
   mov 1,r2
   cmp r0,r1
   jeq cond_os_read_float_30
   clr r2
cond_os_read_float_30:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq if_os_read_float_28
   mov 1,r0
   mov -6,idx
   mov r0,[fp,idx]
   call os_read_char
   clr idx
   mov r0,[fp,idx]
if_os_read_float_28:
   clr idx
   mov [fp,idx],r0
   push r0
   mov 48,r0
   push r0
   pop r1
   pop r0
   mov 1,r2
   cmp r1,r0
   jgt cond_None_33
   clr r2
cond_None_33:
   mov r2,r0
   push r0
   clr idx
   mov [fp,idx],r0
   push r0
   mov 57,r0
   push r0
   pop r1
   pop r0
   mov 1,r2
   cmp r0,r1
   jgt cond_None_35
   clr r2
cond_None_35:
   mov r2,r0
   push r0
   pop r1
   pop r0
   mov 1,r2
   clr r3
   cmp r0,r3
   jgt cond_os_read_float_37
   cmp r1,r3
   jgt cond_os_read_float_37
   clr r2
cond_os_read_float_37:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq if_os_read_float_31
   mov -10,idx
   mov [fp,idx],r0
   push r0
   pop r0
   jmp ret_os_read_float
if_os_read_float_31:
while_os_read_float_38:
   clr idx
   mov [fp,idx],r0
   push r0
   mov 10,r0
   push r0
   pop r1
   pop r0
   clr r2
   cmp r0,r1
   jeq cond_None_40
   inc r2
cond_None_40:
   mov r2,r0
   push r0
   clr idx
   mov [fp,idx],r0
   push r0
   mov 101,r0
   push r0
   pop r1
   pop r0
   clr r2
   cmp r0,r1
   jeq cond_None_41
   inc r2
cond_None_41:
   mov r2,r0
   push r0
   pop r1
   pop r0
   clr r2
   clr r3
   cmp r0,r3
   jeq cond_os_read_float_42
   cmp r1,r3
   jeq cond_os_read_float_42
   inc r2
cond_os_read_float_42:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq while_os_read_float_39
   clr idx
   mov [fp,idx],r0
   push r0
   mov 46,r0
   push r0
   pop r1
   pop r0
   mov 1,r2
   cmp r0,r1
   jeq cond_os_read_float_45
   clr r2
cond_os_read_float_45:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq if_os_read_float_43
   mov 1,r0
   mov -7,idx
   mov r0,[fp,idx]
   call os_read_char
   clr idx
   mov r0,[fp,idx]
   jmp while_os_read_float_38
if_os_read_float_43:
   clr idx
   mov [fp,idx],r0
   push r0
   mov 48,r0
   push r0
   pop r1
   pop r0
   mov 1,r2
   cmp r1,r0
   jgt cond_None_48
   clr r2
cond_None_48:
   mov r2,r0
   push r0
   clr idx
   mov [fp,idx],r0
   push r0
   mov 57,r0
   push r0
   pop r1
   pop r0
   mov 1,r2
   cmp r0,r1
   jgt cond_None_50
   clr r2
cond_None_50:
   mov r2,r0
   push r0
   pop r1
   pop r0
   mov 1,r2
   clr r3
   cmp r0,r3
   jgt cond_os_read_float_52
   cmp r1,r3
   jgt cond_os_read_float_52
   clr r2
cond_os_read_float_52:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq if_os_read_float_46
   mov -10,idx
   mov [fp,idx],r0
   push r0
   pop r0
   jmp ret_os_read_float
if_os_read_float_46:
   clr idx
   mov [fp,idx],r0
   push r0
   mov 48,r0
   push r0
   pop r1
   pop r0
   sub r0,r1,r0
   push r0
   pop r0
   mov -1,idx
   mov r0,[fp,idx]
   mov -1,idx
   mov [fp,idx],r0
   call int_dig_to_flt
   mov -4,idx
   mov r0,[fp,idx]
   mov -7,idx
   mov [fp,idx],r0
   push r0
   clr r0
   push r0
   pop r1
   pop r0
   mov 1,r2
   cmp r0,r1
   jeq cond_os_read_float_55
   clr r2
cond_os_read_float_55:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq if_os_read_float_53
   mov -8,idx
   mov [fp,idx],r0
   push r0
   mov 18688,r0
   push r0
   pop r1
   pop r0
   fmul r0,r1,r0
   push r0
   pop r0
   mov -8,idx
   mov r0,[fp,idx]
   jmp if_os_read_float_54
if_os_read_float_53:
   mov -4,idx
   mov [fp,idx],r0
   push r0
   mov -9,idx
   mov [fp,idx],r0
   push r0
   pop r1
   pop r0
   fdiv r0,r1,r0
   push r0
   pop r0
   mov -4,idx
   mov r0,[fp,idx]
   mov -9,idx
   mov [fp,idx],r0
   push r0
   mov 18688,r0
   push r0
   pop r1
   pop r0
   fmul r0,r1,r0
   push r0
   pop r0
   mov -9,idx
   mov r0,[fp,idx]
if_os_read_float_54:
   mov -8,idx
   mov [fp,idx],r0
   push r0
   mov -4,idx
   mov [fp,idx],r0
   push r0
   pop r1
   pop r0
   fadd r0,r1,r0
   push r0
   pop r0
   mov -8,idx
   mov r0,[fp,idx]
   call os_read_char
   clr idx
   mov r0,[fp,idx]
   jmp while_os_read_float_38
while_os_read_float_39:
   mov -6,idx
   mov [fp,idx],r0
   push r0
   mov 1,r0
   push r0
   pop r1
   pop r0
   mov 1,r2
   cmp r0,r1
   jeq cond_os_read_float_58
   clr r2
cond_os_read_float_58:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq if_os_read_float_56
   mov -8,idx
   mov [fp,idx],r0
   push r0
   mov 15360,r0
   mov 0x8000,r1
   or r0,r1,r0
   push r0
   pop r1
   pop r0
   fmul r0,r1,r0
   push r0
   pop r0
   mov -8,idx
   mov r0,[fp,idx]
if_os_read_float_56:
   clr idx
   mov [fp,idx],r0
   push r0
   mov 10,r0
   push r0
   pop r1
   pop r0
   mov 1,r2
   cmp r0,r1
   jeq cond_os_read_float_61
   clr r2
cond_os_read_float_61:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq if_os_read_float_59
   mov -8,idx
   mov [fp,idx],r0
   push r0
   pop r0
   jmp ret_os_read_float
if_os_read_float_59:
   clr r0
   mov -6,idx
   mov r0,[fp,idx]
   call os_read_char
   clr idx
   mov r0,[fp,idx]
   clr idx
   mov [fp,idx],r0
   push r0
   mov 45,r0
   push r0
   pop r1
   pop r0
   mov 1,r2
   cmp r0,r1
   jeq cond_os_read_float_64
   clr r2
cond_os_read_float_64:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq if_os_read_float_62
   mov 1,r0
   mov -6,idx
   mov r0,[fp,idx]
   call os_read_char
   clr idx
   mov r0,[fp,idx]
if_os_read_float_62:
   clr idx
   mov [fp,idx],r0
   push r0
   mov 48,r0
   push r0
   pop r1
   pop r0
   mov 1,r2
   cmp r1,r0
   jgt cond_None_67
   clr r2
cond_None_67:
   mov r2,r0
   push r0
   clr idx
   mov [fp,idx],r0
   push r0
   mov 57,r0
   push r0
   pop r1
   pop r0
   mov 1,r2
   cmp r0,r1
   jgt cond_None_69
   clr r2
cond_None_69:
   mov r2,r0
   push r0
   pop r1
   pop r0
   mov 1,r2
   clr r3
   cmp r0,r3
   jgt cond_os_read_float_71
   cmp r1,r3
   jgt cond_os_read_float_71
   clr r2
cond_os_read_float_71:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq if_os_read_float_65
   mov -10,idx
   mov [fp,idx],r0
   push r0
   pop r0
   jmp ret_os_read_float
if_os_read_float_65:
   clr idx
   mov [fp,idx],r0
   push r0
   mov 48,r0
   push r0
   pop r1
   pop r0
   sub r0,r1,r0
   push r0
   pop r0
   mov -2,idx
   mov r0,[fp,idx]
   mov -6,idx
   mov [fp,idx],r0
   push r0
   mov 1,r0
   push r0
   pop r1
   pop r0
   mov 1,r2
   cmp r0,r1
   jeq cond_os_read_float_74
   clr r2
cond_os_read_float_74:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq if_os_read_float_72
   mov 11878,r0
   mov -5,idx
   mov r0,[fp,idx]
   jmp if_os_read_float_73
if_os_read_float_72:
   mov 18688,r0
   mov -5,idx
   mov r0,[fp,idx]
if_os_read_float_73:
   clr r0
   mov -3,idx
   mov r0,[fp,idx]
for_os_read_float_75:
   mov -3,idx
   mov [fp,idx],r0
   push r0
   mov -2,idx
   mov [fp,idx],r0
   push r0
   pop r1
   pop r0
   mov 1,r2
   cmp r1,r0
   jgt cond_os_read_float_78
   clr r2
cond_os_read_float_78:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq for_os_read_float_77
   mov -8,idx
   mov [fp,idx],r0
   push r0
   mov -5,idx
   mov [fp,idx],r0
   push r0
   pop r1
   pop r0
   fmul r0,r1,r0
   push r0
   pop r0
   mov -8,idx
   mov r0,[fp,idx]
for_os_read_float_76:
   mov -3,idx
   mov [fp,idx],r0
   push r0
   mov 1,r0
   push r0
   pop r1
   pop r0
   add r0,r1,r0
   push r0
   pop r0
   mov -3,idx
   mov r0,[fp,idx]
   jmp for_os_read_float_75
for_os_read_float_77:
   call os_read_char
   clr idx
   mov r0,[fp,idx]
   clr idx
   mov [fp,idx],r0
   push r0
   mov 10,r0
   push r0
   pop r1
   pop r0
   clr r2
   cmp r0,r1
   jeq cond_os_read_float_82
   inc r2
cond_os_read_float_82:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq if_os_read_float_80
   mov -10,idx
   mov [fp,idx],r0
   push r0
   pop r0
   jmp ret_os_read_float
if_os_read_float_80:
   mov -8,idx
   mov [fp,idx],r0
   push r0
   pop r0
   jmp ret_os_read_float
ret_os_read_float:
   pop idx
   pop idx
   pop idx
   pop idx
   pop idx
   pop idx
   pop idx
   pop idx
   pop idx
   pop idx
   pop idx
   pop idx
   pop fp
   pop lr
   pop idx     ; Restore registers
   pop r4
   pop r3
   pop r2
   pop r1
   ret

;-------------------------------------------------------------
; BIOS - Print a 'float' digit on the display
;
; This is a helper function for 'os_print_float'
;
; Location: ROM addr 0x1620
;
; Input -  R0 = The 'float' digit to be displayed
; Output - R0 = 10 x 'float' digit (used by 'os_print_float')
;
; See 'OS_BIOS.rmg'
;-------------------------------------------------------------

.= 0x1620

print_flt_dig:
   push lr              ; Save used registers
   push r1
   mov 9.0,r1           ; Is val >= 9.0 ?
   fcmp r0,r1
   jlt pfd_test_8
   mov 0x39,r0
   call os_print_char   ; Display '9'
   mov 90.0,r0          ; Return 90.0
   jmp pfd_done
pfd_test_8:
   mov 8.0,r1           ; Is val >= 8.0 ?
   fcmp r0,r1
   jlt pfd_test_7
   mov 0x38,r0
   call os_print_char   ; Display '8'
   mov 80.0,r0          ; Return 80.0
   jmp pfd_done
pfd_test_7:
   mov 7.0,r1           ; Is val >= 7.0 ?
   fcmp r0,r1
   jlt pfd_test_6
   mov 0x37,r0
   call os_print_char   ; Display '7'
   mov 70.0,r0          ; Return 70.0
   jmp pfd_done
pfd_test_6:
   mov 6.0,r1           ; Is val >= 6.0 ?
   fcmp r0,r1
   jlt pfd_test_5
   mov 0x36,r0
   call os_print_char   ; Display '6'
   mov 60.0,r0          ; Return 60.0
   jmp pfd_done
pfd_test_5:
   mov 5.0,r1           ; Is val >= 5.0 ?
   fcmp r0,r1
   jlt pfd_test_4
   mov 0x35,r0
   call os_print_char   ; Display '5'
   mov 50.0,r0          ; Return 50.0
   jmp pfd_done
pfd_test_4:
   mov 4.0,r1           ; Is val >= 4.0 ?
   fcmp r0,r1
   jlt pfd_test_3
   mov 0x34,r0
   call os_print_char   ; Display '4'
   mov 40.0,r0          ; Return 40.0
   jmp pfd_done
pfd_test_3:
   mov 3.0,r1           ; Is val >= 3.0 ?
   fcmp r0,r1
   jlt pfd_test_2
   mov 0x33,r0
   call os_print_char   ; Display '3'
   mov 30.0,r0          ; Return 30.0
   jmp pfd_done
pfd_test_2:
   mov 2.0,r1           ; Is val >= 2.0 ?
   fcmp r0,r1
   jlt pfd_test_1
   mov 0x32,r0
   call os_print_char   ; Display '2'
   mov 20.0,r0          ; Return 20.0
   jmp pfd_done
pfd_test_1:
   mov 1.0,r1           ; Is val >= 1.0 ?
   fcmp r0,r1
   jlt pfd_zero
   mov 0x31,r0
   call os_print_char   ; Display '1'
   mov 10.0,r0          ; Return 10.0
   jmp pfd_done
pfd_zero:
   mov 0x30,r0
   call os_print_char   ; Display '0'
   clr r0               ; Return 0.0
pfd_done:
   pop r1               ; Restore registers
   pop lr
   ret

;------------------------------------------------
; BIOS - Print a 'float' on the display
;
; Location: ROM addr 0x16b0
;
; Input - R0 = The 'float' to be displayed
;
; NB: This code is taken from the auto-generated
;     code produced by compiling 'OS_BIOS.rmg'
;------------------------------------------------

.= 0x16b0

os_print_float:
   push r0     ; Save registers
   push r1
   push r2
   push r3
   push r4
   push idx
   push lr     ; Auto-generated code
   push fp
   push r0
   movsp fp
   clr r0
   push r0
   clr r0
   push r0
   clr r0
   push r0
   clr r0
   push r0
   clr r0
   push r0
   clr r0
   push r0
   mov 1,idx
   mov [fp,idx],r0
   mov -5,idx
   mov r0,[fp,idx]
   mov 1,idx
   mov [fp,idx],r0
   push r0
   mov 32256,r0
   push r0
   pop r1
   pop r0
   mov 1,r2
   cmp r0,r1
   jeq cond_None_121
   clr r2
cond_None_121:
   mov r2,r0
   push r0
   mov 1,idx
   mov [fp,idx],r0
   push r0
   mov 65024,r0
   push r0
   pop r1
   pop r0
   mov 1,r2
   cmp r0,r1
   jeq cond_None_122
   clr r2
cond_None_122:
   mov r2,r0
   push r0
   pop r1
   pop r0
   mov 1,r2
   clr r3
   cmp r0,r3
   jgt cond_os_print_float_123
   cmp r1,r3
   jgt cond_os_print_float_123
   clr r2
cond_os_print_float_123:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq if_os_print_float_119
   mov 78,r0
   call os_print_char
   mov 97,r0
   call os_print_char
   mov 78,r0
   call os_print_char
   clr r0
   jmp ret_os_print_float
if_os_print_float_119:
   mov 1,idx
   mov [fp,idx],r0
   push r0
   mov 31744,r0
   push r0
   pop r1
   pop r0
   mov 1,r2
   cmp r0,r1
   jeq cond_None_126
   clr r2
cond_None_126:
   mov r2,r0
   push r0
   mov 1,idx
   mov [fp,idx],r0
   push r0
   mov 64512,r0
   push r0
   pop r1
   pop r0
   mov 1,r2
   cmp r0,r1
   jeq cond_None_127
   clr r2
cond_None_127:
   mov r2,r0
   push r0
   pop r1
   pop r0
   mov 1,r2
   clr r3
   cmp r0,r3
   jgt cond_os_print_float_128
   cmp r1,r3
   jgt cond_os_print_float_128
   clr r2
cond_os_print_float_128:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq if_os_print_float_124
   mov 1,idx
   mov [fp,idx],r0
   push r0
   mov 31744,r0
   push r0
   pop r1
   pop r0
   mov 1,r2
   cmp r0,r1
   jeq cond_os_print_float_131
   clr r2
cond_os_print_float_131:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq if_os_print_float_129
   mov 43,r0
   call os_print_char
   jmp if_os_print_float_130
if_os_print_float_129:
   mov 45,r0
   call os_print_char
if_os_print_float_130:
   mov 73,r0
   call os_print_char
   mov 110,r0
   call os_print_char
   mov 102,r0
   call os_print_char
   clr r0
   jmp ret_os_print_float
if_os_print_float_124:
   mov 1,idx
   mov [fp,idx],r0
   push r0
   clr r0
   push r0
   pop r1
   pop r0
   mov 1,r2
   cmp r0,r1
   jeq cond_None_134
   clr r2
cond_None_134:
   mov r2,r0
   push r0
   mov 1,idx
   mov [fp,idx],r0
   push r0
   mov 32768,r0
   push r0
   pop r1
   pop r0
   mov 1,r2
   cmp r0,r1
   jeq cond_None_135
   clr r2
cond_None_135:
   mov r2,r0
   push r0
   pop r1
   pop r0
   mov 1,r2
   clr r3
   cmp r0,r3
   jgt cond_os_print_float_136
   cmp r1,r3
   jgt cond_os_print_float_136
   clr r2
cond_os_print_float_136:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq if_os_print_float_132
   mov 48,r0
   call os_print_char
   mov 46,r0
   call os_print_char
   mov 48,r0
   call os_print_char
   clr r0
   jmp ret_os_print_float
if_os_print_float_132:
   mov 1,idx
   mov [fp,idx],r0
   push r0
   clr r0
   push r0
   pop r1
   pop r0
   mov 1,r2
   xor r0,r1,r3
   mov 0x8000,r4
   and r3,r4,r3
   jnz cond_os_print_float_139_2
   and r0,r4,r3
   jz cond_os_print_float_139_2
   mov 0x7fff,r4
   and r0,r4,r3
   and r1,r4,r0
   mov r3,r1
cond_os_print_float_139_2:
   cmp r1,r0
   jgt cond_os_print_float_139
   clr r2
cond_os_print_float_139:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq if_os_print_float_137
   mov 45,r0
   call os_print_char
   mov 1,idx
   mov [fp,idx],r0
   push r0
   mov 15360,r0
   mov 0x8000,r1
   or r0,r1,r0
   push r0
   pop r1
   pop r0
   fmul r0,r1,r0
   push r0
   pop r0
   mov 1,idx
   mov r0,[fp,idx]
if_os_print_float_137:
while_os_print_float_141:
   mov 1,idx
   mov [fp,idx],r0
   push r0
   mov 15360,r0
   push r0
   pop r1
   pop r0
   mov 1,r2
   xor r0,r1,r3
   mov 0x8000,r4
   and r3,r4,r3
   jnz cond_os_print_float_143_2
   and r0,r4,r3
   jz cond_os_print_float_143_2
   mov 0x7fff,r4
   and r0,r4,r3
   and r1,r4,r0
   mov r3,r1
cond_os_print_float_143_2:
   cmp r1,r0
   jgt cond_os_print_float_143
   clr r2
cond_os_print_float_143:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq while_os_print_float_142
   mov -4,idx
   mov [fp,idx],r0
   push r0
   mov 1,r0
   push r0
   pop r1
   pop r0
   sub r0,r1,r0
   push r0
   pop r0
   mov -4,idx
   mov r0,[fp,idx]
   mov 1,idx
   mov [fp,idx],r0
   push r0
   mov 18688,r0
   push r0
   pop r1
   pop r0
   fmul r0,r1,r0
   push r0
   pop r0
   mov 1,idx
   mov r0,[fp,idx]
   jmp while_os_print_float_141
while_os_print_float_142:
while_os_print_float_145:
   mov 1,idx
   mov [fp,idx],r0
   push r0
   mov 18688,r0
   push r0
   pop r1
   pop r0
   mov 1,r2
   xor r0,r1,r3
   mov 0x8000,r4
   and r3,r4,r3
   jnz cond_os_print_float_147_2
   and r0,r4,r3
   jz cond_os_print_float_147_2
   mov 0x7fff,r4
   and r0,r4,r3
   and r1,r4,r0
   mov r3,r1
cond_os_print_float_147_2:
   cmp r0,r1
   jge cond_os_print_float_147
   clr r2
cond_os_print_float_147:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq while_os_print_float_146
   mov -4,idx
   mov [fp,idx],r0
   push r0
   mov 1,r0
   push r0
   pop r1
   pop r0
   add r0,r1,r0
   push r0
   pop r0
   mov -4,idx
   mov r0,[fp,idx]
   mov 1,idx
   mov [fp,idx],r0
   push r0
   mov 18688,r0
   push r0
   pop r1
   pop r0
   fdiv r0,r1,r0
   push r0
   pop r0
   mov 1,idx
   mov r0,[fp,idx]
   jmp while_os_print_float_145
while_os_print_float_146:
   mov -4,idx
   mov [fp,idx],r0
   push r0
   mov 3,r0
   not r0,r0
   inc r0
   push r0
   pop r1
   pop r0
   mov 1,r2
   cmp r1,r0
   jgt cond_None_151
   clr r2
cond_None_151:
   mov r2,r0
   push r0
   mov -4,idx
   mov [fp,idx],r0
   push r0
   mov 3,r0
   push r0
   pop r1
   pop r0
   mov 1,r2
   cmp r0,r1
   jgt cond_None_153
   clr r2
cond_None_153:
   mov r2,r0
   push r0
   pop r1
   pop r0
   mov 1,r2
   clr r3
   cmp r0,r3
   jgt cond_os_print_float_155
   cmp r1,r3
   jgt cond_os_print_float_155
   clr r2
cond_os_print_float_155:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq if_os_print_float_149
   mov 1,idx
   mov [fp,idx],r0
   call print_flt_dig
   mov -3,idx
   mov r0,[fp,idx]
   mov 46,r0
   call os_print_char
   clr r0
   mov -2,idx
   mov r0,[fp,idx]
for_os_print_float_156:
   mov -2,idx
   mov [fp,idx],r0
   push r0
   mov 3,r0
   push r0
   pop r1
   pop r0
   mov 1,r2
   cmp r1,r0
   jgt cond_os_print_float_159
   clr r2
cond_os_print_float_159:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq for_os_print_float_158
   mov 18688,r0
   push r0
   mov 1,idx
   mov [fp,idx],r0
   push r0
   pop r1
   pop r0
   fmul r0,r1,r0
   push r0
   mov -3,idx
   mov [fp,idx],r0
   push r0
   pop r1
   pop r0
   fsub r0,r1,r0
   push r0
   pop r0
   mov 1,idx
   mov r0,[fp,idx]
   mov 1,idx
   mov [fp,idx],r0
   call print_flt_dig
   mov -3,idx
   mov r0,[fp,idx]
for_os_print_float_157:
   mov -2,idx
   mov [fp,idx],r0
   push r0
   mov 1,r0
   push r0
   pop r1
   pop r0
   add r0,r1,r0
   push r0
   pop r0
   mov -2,idx
   mov r0,[fp,idx]
   jmp for_os_print_float_156
for_os_print_float_158:
   mov -4,idx
   mov [fp,idx],r0
   push r0
   clr r0
   push r0
   pop r1
   pop r0
   clr r2
   cmp r0,r1
   jeq cond_os_print_float_163
   inc r2
cond_os_print_float_163:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq if_os_print_float_161
   mov 101,r0
   call os_print_char
   mov -4,idx
   mov [fp,idx],r0
   call os_print_int
if_os_print_float_161:
   jmp if_os_print_float_150
if_os_print_float_149:
   mov -4,idx
   mov [fp,idx],r0
   push r0
   clr r0
   push r0
   pop r1
   pop r0
   mov 1,r2
   cmp r0,r1
   jge cond_os_print_float_166
   clr r2
cond_os_print_float_166:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq if_os_print_float_164
   mov -4,idx
   mov [fp,idx],r0
   push r0
   clr r0
   push r0
   pop r1
   pop r0
   mov 1,r2
   cmp r0,r1
   jeq cond_os_print_float_170
   clr r2
cond_os_print_float_170:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq if_os_print_float_168
   mov 5,r0
   clr idx
   mov r0,[fp,idx]
   mov 1,r0
   mov -1,idx
   mov r0,[fp,idx]
   jmp if_os_print_float_169
if_os_print_float_168:
   mov -4,idx
   mov [fp,idx],r0
   push r0
   mov 4,r0
   push r0
   pop r1
   pop r0
   add r0,r1,r0
   push r0
   pop r0
   clr idx
   mov r0,[fp,idx]
   clr idx
   mov [fp,idx],r0
   push r0
   mov 3,r0
   push r0
   pop r1
   pop r0
   sub r0,r1,r0
   push r0
   pop r0
   mov -1,idx
   mov r0,[fp,idx]
if_os_print_float_169:
   clr r0
   mov -2,idx
   mov r0,[fp,idx]
for_os_print_float_171:
   mov -2,idx
   mov [fp,idx],r0
   push r0
   clr idx
   mov [fp,idx],r0
   push r0
   pop r1
   pop r0
   mov 1,r2
   cmp r1,r0
   jgt cond_os_print_float_174
   clr r2
cond_os_print_float_174:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq for_os_print_float_173
   mov -2,idx
   mov [fp,idx],r0
   push r0
   mov -1,idx
   mov [fp,idx],r0
   push r0
   pop r1
   pop r0
   mov 1,r2
   cmp r0,r1
   jeq cond_os_print_float_178
   clr r2
cond_os_print_float_178:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq if_os_print_float_176
   mov 46,r0
   call os_print_char
   jmp for_os_print_float_172
if_os_print_float_176:
   mov 1,idx
   mov [fp,idx],r0
   call print_flt_dig
   mov -3,idx
   mov r0,[fp,idx]
   mov 18688,r0
   push r0
   mov 1,idx
   mov [fp,idx],r0
   push r0
   pop r1
   pop r0
   fmul r0,r1,r0
   push r0
   mov -3,idx
   mov [fp,idx],r0
   push r0
   pop r1
   pop r0
   fsub r0,r1,r0
   push r0
   pop r0
   mov 1,idx
   mov r0,[fp,idx]
for_os_print_float_172:
   mov -2,idx
   mov [fp,idx],r0
   push r0
   mov 1,r0
   push r0
   pop r1
   pop r0
   add r0,r1,r0
   push r0
   pop r0
   mov -2,idx
   mov r0,[fp,idx]
   jmp for_os_print_float_171
for_os_print_float_173:
   jmp if_os_print_float_165
if_os_print_float_164:
   mov 48,r0
   call os_print_char
   mov 46,r0
   call os_print_char
   mov 1,r0
   not r0,r0
   inc r0
   push r0
   pop r0
   mov -2,idx
   mov r0,[fp,idx]
for_os_print_float_179:
   mov -2,idx
   mov [fp,idx],r0
   push r0
   mov -4,idx
   mov [fp,idx],r0
   push r0
   pop r1
   pop r0
   mov 1,r2
   cmp r0,r1
   jgt cond_os_print_float_182
   clr r2
cond_os_print_float_182:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq for_os_print_float_181
   mov 48,r0
   call os_print_char
for_os_print_float_180:
   mov -2,idx
   mov [fp,idx],r0
   push r0
   mov 1,r0
   push r0
   pop r1
   pop r0
   sub r0,r1,r0
   push r0
   pop r0
   mov -2,idx
   mov r0,[fp,idx]
   jmp for_os_print_float_179
for_os_print_float_181:
   clr r0
   mov -2,idx
   mov r0,[fp,idx]
for_os_print_float_184:
   mov -2,idx
   mov [fp,idx],r0
   push r0
   mov 4,r0
   push r0
   pop r1
   pop r0
   mov 1,r2
   cmp r1,r0
   jgt cond_os_print_float_187
   clr r2
cond_os_print_float_187:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq for_os_print_float_186
   mov 1,idx
   mov [fp,idx],r0
   call print_flt_dig
   mov -3,idx
   mov r0,[fp,idx]
   mov 18688,r0
   push r0
   mov 1,idx
   mov [fp,idx],r0
   push r0
   pop r1
   pop r0
   fmul r0,r1,r0
   push r0
   mov -3,idx
   mov [fp,idx],r0
   push r0
   pop r1
   pop r0
   fsub r0,r1,r0
   push r0
   pop r0
   mov 1,idx
   mov r0,[fp,idx]
for_os_print_float_185:
   mov -2,idx
   mov [fp,idx],r0
   push r0
   mov 1,r0
   push r0
   pop r1
   pop r0
   add r0,r1,r0
   push r0
   pop r0
   mov -2,idx
   mov r0,[fp,idx]
   jmp for_os_print_float_184
for_os_print_float_186:
if_os_print_float_165:
if_os_print_float_150:
ret_os_print_float:
   pop idx
   pop idx
   pop idx
   pop idx
   pop idx
   pop idx
   pop idx
   pop fp
   pop lr
   pop idx     ; Restore registers
   pop r4
   pop r3
   pop r2
   pop r1
   pop r0
   ret

;----------------------------------------------------------------
; BIOS - Terminate a program, and if the error code is non-zero:
;          Display an Error Code on OUT_1
;          Turn on the ERR LED
;
; Location: ROM addr 0x1a90
;
; Input - R0 = Error Code
;----------------------------------------------------------------

.= 0x1a90

os_exit:
   clr r1               ; Error Code = 0 ?
   cmp r0,r1
   jne disp_err
   end                  ; No error - Just stop the program

disp_err:
   mov OUT_1,r1         ; Display the Error Code
   mov IO_START,r2      ; NB: Don't call 'os_disp_out' as we may be in a 'Stack Violation'
   add r1,r2,r1         ;     and so we don't want more PUSHing or POPing
   mov r0,[r1]

   mov 1,r0             ; Turn the ERR LED on
   mov ERR,r1
   mov r0,[r1]

   end                  ; Stop the program

;--------------------------------------------------------------------
; BIOS - Play a tune on the Sound Card
;
; Location: ROM addr 0x1ac0
;
; Inputs - R0 = Address of the 'Notes & Durations' array
;          R1 = Address of the 'Pauses between starting notes' array
;--------------------------------------------------------------------

.= 0x1ac0

os_play_tune:
   push r0              ; Save used registers
   push r1
   push r2
   push r3
   push r4
   push idx
   push lr

   inc r1               ; r1 points to 1st pause
   inc r1

   inc r0               ; r3 = number of notes
   mov [r0],r3

   mov r0,r2            ; r2 points to 1st note
   inc r2

   mov SND,r4           ; r4 = Sound Card address
   clr idx              ; idx = note count = 0

pt_next_note:
   mov [r2,idx],r0      ; Play the next note
   mov r0,[r4]
   mov [r1,idx],r0      ; Wait until pause is over
   call os_delay

   inc idx              ; Played all notes ?
   cmp idx,r3
   jlt pt_next_note

   pop lr               ; Retrieve used registers
   pop idx
   pop r4
   pop r3
   pop r2
   pop r1
   pop r0
   ret

;----------------------------
; BIOS - Delay
;
; Location: ROM addr 0x1af0
;
; Input: R0 - Delay duration
;----------------------------

.= 0x1af0

os_delay:
   push r0              ; Save used registers
   push r1

   clr r1
   cmp r0,r1            ; If 'duration' = 0 we're done
   jeq d_done

d_wait:
   dec r0               ; Keep decrementing 'duration'
   cmp r0,r1            ; until it becomes 0
   jne d_wait

d_done:
   pop r1               ; Retrieve used registers
   pop r0
   ret

