
;-----------------------------------------------------------------------
; BIOS for TimmiOS - The SAL-16 Operating System
;
; It does the following:
;
; a) Jumps to the start of the program in RAM at start up.
;
; b) An Interrupt Vector Table is at 0x0010 & allows for 3 interrupts,
;    generated by the ENTER_1 & ENTER_2 buttons plus the keyboard, with
;    Interrupt Services Routines located at 0xb000, 0xb100 & 0xb200.
;
; c) Contains the BIOS routines.
;-----------------------------------------------------------------------

;---------------------------------------------
; Defines for use in programs using the BIOS:
;
; .equ os_get_in      0x1000
; .equ os_disp_out    0x1030
; .equ os_read_char   0x1050
; .equ os_print_char  0x1080
; .equ os_read_str    0x10a0
; .equ os_print_str   0x10e0
; .equ os_mem_set     0x1110
; .equ os_mem_setn    0x1130
; .equ os_mem_read    0x1150
; .equ os_read_int    0x1170
; .equ os_print_int   0x11d0
; .equ os_read_uint   0x1230
; .equ os_print_uint  0x1280
; .equ os_read_float  0x1330
; .equ os_print_float 0x16b0
; .equ os_exit        0x1a90
;
; .equ IN_1  3
; .equ IN_2  7
; .equ OUT_1 6
; .equ OUT_2 10
;---------------------------------------------

.ROM

; Memory Map
.equ PROG_START 0x8000
.equ IO_START   0xfff0

; Interrupts
.equ INT_ENT_1 0xb000
.equ INT_ENT_2 0xb100
.equ INT_KBD   0xb200

; IO Devices
.equ ERR 0xfff0
.equ KBD 0xfff1
.equ TTY 0xfff2

.equ IN_1  3
.equ IN_2  7
.equ OUT_1 6
.equ OUT_2 10

; ASCII Chars
.equ CHR_ENT   0x0a
.equ CHR_MINUS 0x2d
.equ CHR_ZERO  0x30

; Error Codes
.equ DIV_BY_0     0x0100
.equ POW_UNDEF    0x0110
.equ BAD_INT      0x0120
.equ INV_DATA     0x0130
.equ BAD_VEC_DIMS 0x0140
.equ BAD_MAT_DIMS 0x0150
.equ LN_LTE_ZERO  0x0160

; SAL-16I Error Code
.equ NO_FPU 0x0f00

; Misc
.equ TRUE  1
.equ FALSE 0

.equ GET_INT_NUM 4         ; To show up to 5 digits when displayed integers on the text screen
.equ MAX_SIGN_INT 0x7fff   ; The maximum signed integer

.code

;-------------------------------
; Goto the start of the program
;-------------------------------

jmp PROG_START

;------------------------
; Interrupt Vector Table
;------------------------

.= 0x0010
   jmp INT_ENT_1
   jmp INT_ENT_2
   jmp INT_KBD
   jmp NO_FPU              ; Only for SAL-16I

;----------------
; Error Handling
;----------------

; Display error code on OUT_1, turn on ERR LED & stop

; Division by 0
.= 0x0100
   ldi r0,DIV_BY_0
   jmp os_exit

; Undefined power: 0^0
.= 0x0110
   ldi r0,POW_UNDEF
   jmp os_exit

; Integer not in range
.= 0x0120
   ldi r0,BAD_INT
   jmp os_exit

; Invalid input data
.= 0x0130
   ldi r0,INV_DATA
   jmp os_exit

; Bad vector dimensions
.= 0x0140
   ldi r0,BAD_VEC_DIMS
   jmp os_exit

; Bad matrix dimensions
.= 0x0150
   ldi r0,BAD_MAT_DIMS
   jmp os_exit

; ln(x) with x <= 0.0
.= 0x0160
   ldi r0,LN_LTE_ZERO
   jmp os_exit

; No FPU available for floating point instructions (only used by SAL-16I)
.= 0x0f00
   ldi r0,NO_FPU
   jmp os_exit

;------------------------------------------------
; BIOS - Get a word from IN_1 or IN_2
;
; Location: ROM addr 0x1000
;
; Input  - R0 = Device ID: 3 (IN_1) or 7 (IN_2)
; Output - R0 = Entered word
;------------------------------------------------

.= 0x1000

os_get_in:
   push r3              ; Save used registers
   push r2
   push r1

   clr r1               ; r1 = 0
   clr r2               ; r2 = 0
   ldi r3,IO_START      ; r3 = 0xfff0 (the start of I/O memory)
   add r0,r3,r3         ; r3 now points to IN_x

   add r3,r1,r1
   inc r1               ; r1 points to WAIT_x (the 'waiting' LED)

   add r1,r2,r2         ; r2 points to ENTER_x (the enter button)
   inc r2

   ldi r0,1             ; Turn the LED on
   st r0,[r1]
   push r1              ; Store the WAIT_x addr on the stack

in_chk_ent:
   ld r1,[r2]           ; Put the button state in r1
   cmp r0,r1
   jgt in_chk_ent       ; Stay in the 'check_enter loop' until the button is pressed

   pop r1               ; Retrieve the WAIT_x addr from the stack
   clr r0
   st r0,[r1]           ; Turn off the LED
   ld r0,[r3]           ; r0 = IN_x

   pop r1               ; Retrieve registers
   pop r2
   pop r3
   ret

;-------------------------------------------------
; BIOS - Display a word on OUT_1 or OUT_2
;
; Location: ROM addr 0x1030
;
; Input - R0 = Device ID: 6 (OUT_1) or 10 (OUT_2)
;         R1 = Value to be displayed
;-------------------------------------------------

.= 0x1030

os_disp_out:
   push r2              ; Save used register

   ldi r2,IO_START      ; r2 holds the device addr
   add r2,r0,r0
   st r1,[r0]           ; Store display val to device addr

   pop r2               ; Retrieve register
   ret

;-------------------------------------------
; BIOS - Read a character from the keyboard
;
; Location: ROM addr 0x1050
;
; Output - R0 = The character read
;-------------------------------------------

.= 0x1050

os_read_char:
   push r3              ; Save used registers
   push r2
   push r1

   ldi r2,KBD
   ldi r3,TTY
   clr r1               ; r1 is used to test for an available char

gc_rd_val:
   ld r0,[r2]           ; Read a char from the keyboard
   cmp r0,r1            ; Got a char ?
   jeq gc_rd_val        ; No char - try another read     

   st r0,[r3]           ; Display the char

   pop r1               ; Retrieve registers
   pop r2
   pop r3
   ret

;--------------------------------------------
; BIOS - Print a character on the display
;
; Location: ROM addr 0x1080
;
; Input - R0 = The character to be displayed
;--------------------------------------------

.= 0x1080

os_print_char:
   push r1              ; Save used register

   ldi r1,TTY
   st r0,[r1]           ; Display the char

   pop r1               ; Retrieve register
   ret

;-----------------------------------------
; BIOS - Read a string from the keyboard
;
; Location: ROM addr 0x10a0
;
; Input - R0 = Address of the string read
;-----------------------------------------

.= 0x10a0

os_read_str:
   push fp             ; Save used registers
   push idx
   push r4
   push r3
   push r2
   push r1
   push r0

   mov r0,r1
   ldi r2,0x0a          ; 'LF'
   ldi r3,TTY
   ldi r4,KBD
   clr idx
   clr fp               ; fp is used to test for an available char

gs_next:
   ld r0,[r4]           ; Read a char from the keyboard
   cmp r0,fp            ; Got a char ?
   jeq gs_next          ; No char - try another read     

   cmp r0,r2            ; We're done if it's a LF
   jeq gs_done
   st r0,[r3]           ; Display the char
   stx r0,[r1,idx]      ; Store the char
   inc idx
   jmp gs_next

gs_done:
   clr r2
   stx r2,[r1,idx]      ; Store null (string terminator)

   pop r0               ; Retrieve registers
   pop r1
   pop r2
   pop r3
   pop r4
   pop idx
   pop fp
   ret

;--------------------------------------------------------
; BIOS - Print a string on the display
;
; Location: ROM addr 0x10e0
;
; Input - R0 = The address of the string to be displayed
;--------------------------------------------------------

.= 0x10e0

os_print_str:
   push idx             ; Save used registers
   push r3
   push r2
   push r1

   ldi r1,TTY
   clr idx
   clr r3               ; r3 is used to test for null (end of string)

ps_next:
   ldx r2,[r0,idx]      ; Get the next char from memory
   cmp r2,r3            ; If it's a null we're done
   jeq ps_done
   st r2,[r1]           ; Print the char
   inc idx
   jmp ps_next

ps_done:
   pop r1               ; Retrieve registers
   pop r2
   pop r3
   pop idx
   ret

;---------------------------
; BIOS - Memory Set
;
; Location: ROM addr 0x1110
;
; Inputs: R0 = address
;         R1 = value
;---------------------------

.= 0x1110

os_mem_set:
	st r1,[r0]           ; Store value to address
   ret

;-------------------------------
; BIOS - Memory Region Set
;
; Location: ROM addr 0x1130
;
; Inputs: R0 = starting address
;         R1 = number of bytes
;         R2 = value
;-------------------------------

.= 0x1130

os_mem_setn:
   push idx             ; Save used register

   clr idx

ms_loop:
   cmp idx,r1           ; Done the whole region ?
   jeq ms_done
	stx r2,[r0,idx]      ; Store value to address
   inc idx
   jmp ms_loop

ms_done:
   pop idx              ; Retrieve register
   ret

;---------------------------
; BIOS - Memory Read
;
; Location: ROM addr 0x1150
;
; Inputs: R0 = address
; Output: R0 = value
;---------------------------

.= 0x1150

os_mem_read:
   push r1              ; Save used register

	ld r1,[r0]	         ; Read value at address
	mov r1,r0	         ; Return value

   pop r1               ; Retrieve register
   ret

;------------------------------------------------
; BIOS - Read a signed integer from the keyboard
;
; Location: ROM addr 0x1170
;
; Output - R0 = The signed integer read
;------------------------------------------------

.= 0x1170

os_read_int:
   push lr              ; Save used registers
   push fp
   push idx
   push r4
   push r3
   push r2
   push r1

   clr r2               ; number (r2) = 0
   ldi r4,FALSE         ; Clear 'minus flag' (r4)
   clr idx              ; char count (idx) = 0
   ldi r1,10            ; r1 is used to store 10 for digit multiplication & to test digit limit

gi_next_char:
   ldi fp,KBD           ; Read a char from the keyboard
   ld r0,[fp]
   clr lr               ; Got a char ?
   cmp r0,lr
   jeq gi_next_char     ; No char - try another read     

   inc idx              ; char count += 1

   ldi r3,CHR_ENT       ; Is it the 'Enter' key ? 
   cmp r0,r3
   jeq gi_done

   ldi fp,TTY           ; Display char on text screen
   st r0,[fp]

   ldi r3,CHR_MINUS     ; Is it the '-' key ? 
   cmp r0,r3
   jne gi_read_next
   ldi lr,1             ; '-' only allowed as the 1st char
   cmp idx,lr
   jne gi_bad_char
   ldi r4,TRUE          ; Set 'minus' flag
   jmp gi_next_char

gi_read_next:
   ldi r3,CHR_ZERO      ; r0 is the next digit (char - CHR_ZERO)
   sub r0,r3,r0
   jmi gi_bad_char      ; digit < 0 ? - If so it's invalid
   cmp r0,r1            ; digit > 9 ? - If so it's invalid
   jge gi_bad_char

   mul r2,r1,r2         ; Update the number with the digit 
   add r2,r0,r2

   ldi r3,MAX_SIGN_INT  ; Check it's a valid number (-32,767 -> 32,767)
   cmp r2,r3
   jle gi_next_char

	jmp BAD_INT          ; The number's out of range

gi_done:
   ldi lr,FALSE
   cmp r4,lr            ; Is it a negative number ?
   jeq gi_pos
   not r2,r2            ; Negate number
   inc r2

gi_pos:
   mov r2,r0            ; r0 = number
   pop r1               ; Restore registers & return
   pop r2
   pop r3
   pop r4
   pop idx
   pop fp
   pop lr
	ret

gi_bad_char:
   clr r2               ; Just set number = 0 on an invalid char
   jmp gi_done

;-------------------------------------------------
; BIOS - Print a signed integer on the display
;
; Location: ROM addr 0x11d0
;
; Input - R0 = The signed integer to be displayed
;-------------------------------------------------

.= 0x11d0

os_print_int:
   push lr              ; Save used registers
   push fp
   push idx
   push r4
   push r3
   push r2
   push r1
   push r0

   ldi r4,TTY           ; r4 = Display address
   ldi fp,CHR_ZERO      ; fp = ASCII '0'

   clr r1               ; Determine if number < 0, = 0 or > 0 ?
   add r0,r1,r0
   jeq pi_zero
   jpl pi_pos

   ldi r1,CHR_MINUS     ; Display '-'
   st r1,[r4]
   not r0,r0            ; r0 = abs(number)
   inc r0

pi_pos:
   ldi idx,GET_INT_NUM  ; Initialise digit count
   ldi r2,10            ; Divisor (r2) = 10
   ldi r3,TRUE          ; Set 'leading zero' flag

pi_next_dig:
   udiv r0,r2,r1        ; Remainder (r1) is the next decimal digit - this is doing: r1 = r0 % r2
   mul r1,r2,r1
   sub r0,r1,r1

   add r1,fp,r1         ; r1 = ASCII value for the digit
   push r1              ; Save the digit char on the stack
   udiv r0,r2,r0        ; Divide r0 by 10
   dec idx
   jmi pi_disp          ; Done all digits ?
   jmp pi_next_dig

pi_disp:                ; Display the decimal digits 
   ldi idx,GET_INT_NUM
   ldi lr,TRUE

pi_next_char:
   pop r0   	         ; Get the next char

   cmp r0,fp            ; Is the char a leading zero ?
   jne pi_disp_char
   cmp r3,lr
   jeq pi_lead_zero     ; Don't display leading zeros

pi_disp_char:
   ldi r3,FALSE         ; Clear 'leading zero' flag
   st r0,[r4]           ; Display the char

pi_lead_zero:
   dec idx
   jmi pi_done          ; Displayed all chars ?
   jmp pi_next_char

pi_zero:
   ldi r0,CHR_ZERO      ; Display '0'
   st r0,[r4]
   
pi_done:
   pop r0               ; Restore registers & return
   pop r1
   pop r2
   pop r3
   pop r4
   pop idx
   pop fp
   pop lr
   ret

;---------------------------------------------------
; BIOS - Read an unsigned integer from the keyboard
;
; Location: ROM addr 0x1230
;
; Output - R0 = The unsigned integer read
;---------------------------------------------------

.= 0x1230

os_read_uint:
   push lr              ; Save used registers
   push fp
   push idx
   push r4
   push r3
   push r2
   push r1

   clr r2               ; number (r2) = 0
   ldi r1,10            ; r1 is used to store 10 for digit multiplication & to test digit limit
   ldi r3,CHR_ENT
   ldi r4,CHR_ZERO
   ldi idx,KBD
   ldi fp,TTY
   clr lr               ; lr is used for char detection

gu_next_char:
   ld r0,[idx]          ; Read a char from the keyboard
   cmp r0,lr            ; Got a char ?
   jeq gu_next_char     ; No char - try another read     

   cmp r0,r3            ; Is it the 'Enter' key ? 
   jeq gu_done

   st r0,[fp]           ; Display char on text screen

   sub r0,r4,r0         ; r0 is the next digit (char - CHR_ZERO)
   jmi gu_err           ; digit < 0 ? - If so it's invalid
   cmp r0,r1            ; digit > 9 ? - If so it's invalid
   jge gu_err

   mul r2,r1,r2         ; Update the number with the digit
   jc gu_err            ; Checking it's not out of range
   add r2,r0,r2
   jc gu_err

   jmp gu_next_char

gu_err:
	jmp BAD_INT          ; An invalid char or the number's out of range

gu_done:
   mov r2,r0            ; r0 = number
   pop r1               ; Restore registers & return
   pop r2
   pop r3
   pop r4
   pop idx
   pop fp
   pop lr
	ret

;---------------------------------------------------
; BIOS - Print an unsigned integer on the display
;
; Location: ROM addr 0x1280
;
; Input - R0 = The unsigned integer to be displayed
;---------------------------------------------------

.= 0x1280

os_print_uint:
   push lr              ; Save used registers
   push fp
   push idx
   push r4
   push r3
   push r2
   push r1
   push r0

   ldi r4,TTY           ; r4 = Display address

   clr r1               ; Is number = 0 ?
   add r0,r1,r0
   jeq pu_zero

   ldi idx,GET_INT_NUM  ; Initialise digit count
   ldi fp,CHR_ZERO      ; fp = ASCII '0'
   ldi r2,10

pu_next_dig:
   udiv r0,r2,r1        ; Remainder (r1) is the next decimal digit - this is doing: r1 = r0 % r2
   mul r1,r2,r1
   sub r0,r1,r1

   add r1,fp,r1         ; r1 = ASCII value for the digit
   push r1              ; Save the digit char on the stack
   udiv r0,r2,r0        ; Divide r0 by 10
   dec idx
   jmi pu_disp          ; Done all digits ?
   jmp pu_next_dig

pu_disp:                ; Display the decimal digits
   ldi idx,GET_INT_NUM  ; Initialise digit count
   ldi r3,TRUE          ; Set 'leading zero' flag
   ldi lr,TRUE          

pu_next_char:
   pop r0   	         ; Get the next char

   cmp r0,fp            ; Is the char a leading zero ?
   jne pu_disp_char
   cmp r3,lr
   jeq pu_lead_zero     ; Don't display leading zeros

pu_disp_char:
   ldi r3,FALSE         ; Clear 'leading zero' flag
   st r0,[r4]           ; Display the char

pu_lead_zero:
   dec idx
   jmi pu_done          ; Displayed all chars ?
   jmp pu_next_char

pu_zero:
   ldi r0,CHR_ZERO      ; Display '0'
   st r0,[r4]
   
pu_done:
   pop r0               ; Restore registers & return
   pop r1
   pop r2
   pop r3
   pop r4
   pop idx
   pop fp
   pop lr
   ret

;-----------------------------------------------
; BIOS - Convert an 'int' digit to a 'float'
;
; This is a helper function for 'os_read_float'
;
; Location: ROM addr 0x12d0
;
; Input  - R0 = The 'int' digit to be converted
; Output - R0 = The resulting 'float' digit
;
; See 'OS_BIOS.rmg'
;-----------------------------------------------

.= 0x12d0

int_dig_to_flt:
   push r1              ; Save used register
   ldi r1,9             ; Is val = 9 ?
   cmp r0,r1
   jne idtf_test_8
   ldi r0,9.0           ; Return 9.0
   jmp idtf_done
idtf_test_8:
   dec r1               ; Is val = 8 ?
   cmp r0,r1
   jne idtf_test_7
   ldi r0,8.0           ; Return 8.0
   jmp idtf_done
idtf_test_7:
   dec r1               ; Is val = 7 ?
   cmp r0,r1
   jne idtf_test_6
   ldi r0,7.0           ; Return 7.0
   jmp idtf_done
idtf_test_6:
   dec r1               ; Is val = 6 ?
   cmp r0,r1
   jne idtf_test_5
   ldi r0,6.0           ; Return 6.0
   jmp idtf_done
idtf_test_5:
   dec r1               ; Is val = 5 ?
   cmp r0,r1
   jne idtf_test_4
   ldi r0,5.0           ; Return 5.0
   jmp idtf_done
idtf_test_4:
   dec r1               ; Is val = 4 ?
   cmp r0,r1
   jne idtf_test_3
   ldi r0,4.0           ; Return 4.0
   jmp idtf_done
idtf_test_3:
   dec r1               ; Is val = 3 ?
   cmp r0,r1
   jne idtf_test_2
   ldi r0,3.0           ; Return 3.0
   jmp idtf_done
idtf_test_2:
   dec r1               ; Is val = 2 ?
   cmp r0,r1
   jne idtf_test_1
   ldi r0,2.0           ; Return 2.0
   jmp idtf_done
idtf_test_1:
   dec r1               ; Is val = 1 ?
   cmp r0,r1
   jne idtf_zero
   ldi r0,1.0           ; Return 1.0
   jmp idtf_done
idtf_zero:
   clr r0               ; Return 0.0
idtf_done:
   pop r1               ; Restore register
   ret

;------------------------------------------------
; BIOS - Read a 'float' number from the keyboard
;
; Location: ROM addr 0x1330
;
; Output - R0 = The 'float' number
;
; NB: This code is taken from the auto-generated
;     code produced by compiling 'OS_BIOS.rmg'
;------------------------------------------------

.= 0x1330

os_read_float:
   push r1     ; Save registers
   push r2
   push r3
   push r4
   push idx
   push lr     ; Auto-generated code
   push fp
   movsp fp
   clr r0
   push r0
   clr r0
   push r0
   clr r0
   push r0
   clr r0
   push r0
   clr r0
   push r0
   clr r0
   push r0
   clr r0
   push r0
   clr r0
   push r0
   clr r0
   push r0
   ldi r0,18688
   push r0
   clr r0
   push r0
   clr r0
   push r0
   ldi idx,-10
   add fp,idx,r0
   ldi idx,-11
   stx r0,[fp,idx]
   ldi idx,-11
   ldx r0,[fp,idx]
   ldi r1,32256
   call os_mem_set
   call os_read_char
   ldi idx,0
   stx r0,[fp,idx]
   ldi idx,0
   ldx r0,[fp,idx]
   push r0
   ldi r0,45
   push r0
   pop r1
   pop r0
   ldi r2,1
   cmp r0,r1
   jeq cond_os_read_float_30
   clr r2
cond_os_read_float_30:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq if_os_read_float_28
   ldi r0,1
   ldi idx,-6
   stx r0,[fp,idx]
   call os_read_char
   ldi idx,0
   stx r0,[fp,idx]
if_os_read_float_28:
   ldi idx,0
   ldx r0,[fp,idx]
   push r0
   ldi r0,48
   push r0
   pop r1
   pop r0
   ldi r2,1
   cmp r1,r0
   jgt cond_None_33
   clr r2
cond_None_33:
   mov r2,r0
   push r0
   ldi idx,0
   ldx r0,[fp,idx]
   push r0
   ldi r0,57
   push r0
   pop r1
   pop r0
   ldi r2,1
   cmp r0,r1
   jgt cond_None_35
   clr r2
cond_None_35:
   mov r2,r0
   push r0
   pop r1
   pop r0
   ldi r2,1
   clr r3
   cmp r0,r3
   jgt cond_os_read_float_37
   cmp r1,r3
   jgt cond_os_read_float_37
   clr r2
cond_os_read_float_37:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq if_os_read_float_31
   ldi idx,-10
   ldx r0,[fp,idx]
   push r0
   pop r0
   jmp ret_os_read_float
if_os_read_float_31:
while_os_read_float_38:
   ldi idx,0
   ldx r0,[fp,idx]
   push r0
   ldi r0,10
   push r0
   pop r1
   pop r0
   clr r2
   cmp r0,r1
   jeq cond_None_40
   inc r2
cond_None_40:
   mov r2,r0
   push r0
   ldi idx,0
   ldx r0,[fp,idx]
   push r0
   ldi r0,101
   push r0
   pop r1
   pop r0
   clr r2
   cmp r0,r1
   jeq cond_None_41
   inc r2
cond_None_41:
   mov r2,r0
   push r0
   pop r1
   pop r0
   clr r2
   clr r3
   cmp r0,r3
   jeq cond_os_read_float_42
   cmp r1,r3
   jeq cond_os_read_float_42
   inc r2
cond_os_read_float_42:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq while_os_read_float_39
   ldi idx,0
   ldx r0,[fp,idx]
   push r0
   ldi r0,46
   push r0
   pop r1
   pop r0
   ldi r2,1
   cmp r0,r1
   jeq cond_os_read_float_45
   clr r2
cond_os_read_float_45:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq if_os_read_float_43
   ldi r0,1
   ldi idx,-7
   stx r0,[fp,idx]
   call os_read_char
   ldi idx,0
   stx r0,[fp,idx]
   jmp while_os_read_float_38
if_os_read_float_43:
   ldi idx,0
   ldx r0,[fp,idx]
   push r0
   ldi r0,48
   push r0
   pop r1
   pop r0
   ldi r2,1
   cmp r1,r0
   jgt cond_None_48
   clr r2
cond_None_48:
   mov r2,r0
   push r0
   ldi idx,0
   ldx r0,[fp,idx]
   push r0
   ldi r0,57
   push r0
   pop r1
   pop r0
   ldi r2,1
   cmp r0,r1
   jgt cond_None_50
   clr r2
cond_None_50:
   mov r2,r0
   push r0
   pop r1
   pop r0
   ldi r2,1
   clr r3
   cmp r0,r3
   jgt cond_os_read_float_52
   cmp r1,r3
   jgt cond_os_read_float_52
   clr r2
cond_os_read_float_52:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq if_os_read_float_46
   ldi idx,-10
   ldx r0,[fp,idx]
   push r0
   pop r0
   jmp ret_os_read_float
if_os_read_float_46:
   ldi idx,0
   ldx r0,[fp,idx]
   push r0
   ldi r0,48
   push r0
   pop r1
   pop r0
   sub r0,r1,r0
   push r0
   pop r0
   ldi idx,-1
   stx r0,[fp,idx]
   ldi idx,-1
   ldx r0,[fp,idx]
   call int_dig_to_flt
   ldi idx,-4
   stx r0,[fp,idx]
   ldi idx,-7
   ldx r0,[fp,idx]
   push r0
   ldi r0,0
   push r0
   pop r1
   pop r0
   ldi r2,1
   cmp r0,r1
   jeq cond_os_read_float_55
   clr r2
cond_os_read_float_55:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq if_os_read_float_53
   ldi idx,-8
   ldx r0,[fp,idx]
   push r0
   ldi r0,18688
   push r0
   pop r1
   pop r0
   fmul r0,r1,r0
   push r0
   pop r0
   ldi idx,-8
   stx r0,[fp,idx]
   jmp if_os_read_float_54
if_os_read_float_53:
   ldi idx,-4
   ldx r0,[fp,idx]
   push r0
   ldi idx,-9
   ldx r0,[fp,idx]
   push r0
   pop r1
   pop r0
   fdiv r0,r1,r0
   push r0
   pop r0
   ldi idx,-4
   stx r0,[fp,idx]
   ldi idx,-9
   ldx r0,[fp,idx]
   push r0
   ldi r0,18688
   push r0
   pop r1
   pop r0
   fmul r0,r1,r0
   push r0
   pop r0
   ldi idx,-9
   stx r0,[fp,idx]
if_os_read_float_54:
   ldi idx,-8
   ldx r0,[fp,idx]
   push r0
   ldi idx,-4
   ldx r0,[fp,idx]
   push r0
   pop r1
   pop r0
   fadd r0,r1,r0
   push r0
   pop r0
   ldi idx,-8
   stx r0,[fp,idx]
   call os_read_char
   ldi idx,0
   stx r0,[fp,idx]
   jmp while_os_read_float_38
while_os_read_float_39:
   ldi idx,-6
   ldx r0,[fp,idx]
   push r0
   ldi r0,1
   push r0
   pop r1
   pop r0
   ldi r2,1
   cmp r0,r1
   jeq cond_os_read_float_58
   clr r2
cond_os_read_float_58:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq if_os_read_float_56
   ldi idx,-8
   ldx r0,[fp,idx]
   push r0
   ldi r0,15360
   ldi r1,0x8000
   or r0,r1,r0
   push r0
   pop r1
   pop r0
   fmul r0,r1,r0
   push r0
   pop r0
   ldi idx,-8
   stx r0,[fp,idx]
if_os_read_float_56:
   ldi idx,0
   ldx r0,[fp,idx]
   push r0
   ldi r0,10
   push r0
   pop r1
   pop r0
   ldi r2,1
   cmp r0,r1
   jeq cond_os_read_float_61
   clr r2
cond_os_read_float_61:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq if_os_read_float_59
   ldi idx,-8
   ldx r0,[fp,idx]
   push r0
   pop r0
   jmp ret_os_read_float
if_os_read_float_59:
   ldi r0,0
   ldi idx,-6
   stx r0,[fp,idx]
   call os_read_char
   ldi idx,0
   stx r0,[fp,idx]
   ldi idx,0
   ldx r0,[fp,idx]
   push r0
   ldi r0,45
   push r0
   pop r1
   pop r0
   ldi r2,1
   cmp r0,r1
   jeq cond_os_read_float_64
   clr r2
cond_os_read_float_64:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq if_os_read_float_62
   ldi r0,1
   ldi idx,-6
   stx r0,[fp,idx]
   call os_read_char
   ldi idx,0
   stx r0,[fp,idx]
if_os_read_float_62:
   ldi idx,0
   ldx r0,[fp,idx]
   push r0
   ldi r0,48
   push r0
   pop r1
   pop r0
   ldi r2,1
   cmp r1,r0
   jgt cond_None_67
   clr r2
cond_None_67:
   mov r2,r0
   push r0
   ldi idx,0
   ldx r0,[fp,idx]
   push r0
   ldi r0,57
   push r0
   pop r1
   pop r0
   ldi r2,1
   cmp r0,r1
   jgt cond_None_69
   clr r2
cond_None_69:
   mov r2,r0
   push r0
   pop r1
   pop r0
   ldi r2,1
   clr r3
   cmp r0,r3
   jgt cond_os_read_float_71
   cmp r1,r3
   jgt cond_os_read_float_71
   clr r2
cond_os_read_float_71:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq if_os_read_float_65
   ldi idx,-10
   ldx r0,[fp,idx]
   push r0
   pop r0
   jmp ret_os_read_float
if_os_read_float_65:
   ldi idx,0
   ldx r0,[fp,idx]
   push r0
   ldi r0,48
   push r0
   pop r1
   pop r0
   sub r0,r1,r0
   push r0
   pop r0
   ldi idx,-2
   stx r0,[fp,idx]
   ldi idx,-6
   ldx r0,[fp,idx]
   push r0
   ldi r0,1
   push r0
   pop r1
   pop r0
   ldi r2,1
   cmp r0,r1
   jeq cond_os_read_float_74
   clr r2
cond_os_read_float_74:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq if_os_read_float_72
   ldi r0,11878
   ldi idx,-5
   stx r0,[fp,idx]
   jmp if_os_read_float_73
if_os_read_float_72:
   ldi r0,18688
   ldi idx,-5
   stx r0,[fp,idx]
if_os_read_float_73:
   ldi r0,0
   ldi idx,-3
   stx r0,[fp,idx]
for_os_read_float_75:
   ldi idx,-3
   ldx r0,[fp,idx]
   push r0
   ldi idx,-2
   ldx r0,[fp,idx]
   push r0
   pop r1
   pop r0
   ldi r2,1
   cmp r1,r0
   jgt cond_os_read_float_78
   clr r2
cond_os_read_float_78:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq for_os_read_float_77
   ldi idx,-8
   ldx r0,[fp,idx]
   push r0
   ldi idx,-5
   ldx r0,[fp,idx]
   push r0
   pop r1
   pop r0
   fmul r0,r1,r0
   push r0
   pop r0
   ldi idx,-8
   stx r0,[fp,idx]
for_os_read_float_76:
   ldi idx,-3
   ldx r0,[fp,idx]
   push r0
   ldi r0,1
   push r0
   pop r1
   pop r0
   add r0,r1,r0
   push r0
   pop r0
   ldi idx,-3
   stx r0,[fp,idx]
   jmp for_os_read_float_75
for_os_read_float_77:
   call os_read_char
   ldi idx,0
   stx r0,[fp,idx]
   ldi idx,0
   ldx r0,[fp,idx]
   push r0
   ldi r0,10
   push r0
   pop r1
   pop r0
   clr r2
   cmp r0,r1
   jeq cond_os_read_float_82
   inc r2
cond_os_read_float_82:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq if_os_read_float_80
   ldi idx,-10
   ldx r0,[fp,idx]
   push r0
   pop r0
   jmp ret_os_read_float
if_os_read_float_80:
   ldi idx,-8
   ldx r0,[fp,idx]
   push r0
   pop r0
   jmp ret_os_read_float
ret_os_read_float:
   pop idx
   pop idx
   pop idx
   pop idx
   pop idx
   pop idx
   pop idx
   pop idx
   pop idx
   pop idx
   pop idx
   pop idx
   pop fp
   pop lr
   pop idx     ; Restore registers
   pop r4
   pop r3
   pop r2
   pop r1
   ret

;-------------------------------------------------------------
; BIOS - Print a 'float' digit on the display
;
; This is a helper function for 'os_print_float'
;
; Location: ROM addr 0x1620
;
; Input -  R0 = The 'float' digit to be displayed
; Output - R0 = 10 x 'float' digit (used by 'os_print_float')
;
; See 'OS_BIOS.rmg'
;-------------------------------------------------------------

.= 0x1620

print_flt_dig:
   push lr              ; Save used registers
   push r1
   ldi r1,9.0           ; Is val >= 9.0 ?
   cmp r0,r1
   jlt pfd_test_8
   ldi r0,0x39
   call os_print_char   ; Display '9'
   ldi r0,90.0          ; Return 90.0
   jmp pfd_done
pfd_test_8:
   ldi r1,8.0           ; Is val >= 8.0 ?
   cmp r0,r1
   jlt pfd_test_7
   ldi r0,0x38
   call os_print_char   ; Display '8'
   ldi r0,80.0          ; Return 80.0
   jmp pfd_done
pfd_test_7:
   ldi r1,7.0           ; Is val >= 7.0 ?
   cmp r0,r1
   jlt pfd_test_6
   ldi r0,0x37
   call os_print_char   ; Display '7'
   ldi r0,70.0          ; Return 70.0
   jmp pfd_done
pfd_test_6:
   ldi r1,6.0           ; Is val >= 6.0 ?
   cmp r0,r1
   jlt pfd_test_5
   ldi r0,0x36
   call os_print_char   ; Display '6'
   ldi r0,60.0          ; Return 60.0
   jmp pfd_done
pfd_test_5:
   ldi r1,5.0           ; Is val >= 5.0 ?
   cmp r0,r1
   jlt pfd_test_4
   ldi r0,0x35
   call os_print_char   ; Display '5'
   ldi r0,50.0          ; Return 50.0
   jmp pfd_done
pfd_test_4:
   ldi r1,4.0           ; Is val >= 4.0 ?
   cmp r0,r1
   jlt pfd_test_3
   ldi r0,0x34
   call os_print_char   ; Display '4'
   ldi r0,40.0          ; Return 40.0
   jmp pfd_done
pfd_test_3:
   ldi r1,3.0           ; Is val >= 3.0 ?
   cmp r0,r1
   jlt pfd_test_2
   ldi r0,0x33
   call os_print_char   ; Display '3'
   ldi r0,30.0          ; Return 30.0
   jmp pfd_done
pfd_test_2:
   ldi r1,2.0           ; Is val >= 2.0 ?
   cmp r0,r1
   jlt pfd_test_1
   ldi r0,0x32
   call os_print_char   ; Display '2'
   ldi r0,20.0          ; Return 20.0
   jmp pfd_done
pfd_test_1:
   ldi r1,1.0           ; Is val >= 1.0 ?
   cmp r0,r1
   jlt pfd_zero
   ldi r0,0x31
   call os_print_char   ; Display '1'
   ldi r0,10.0          ; Return 10.0
   jmp pfd_done
pfd_zero:
   ldi r0,0x30
   call os_print_char   ; Display '0'
   clr r0               ; Return 0.0
pfd_done:
   pop r1               ; Restore registers
   pop lr
   ret

;------------------------------------------------
; BIOS - Print a 'float' on the display
;
; Location: ROM addr 0x16b0
;
; Input - R0 = The 'float' to be displayed
;
; NB: This code is taken from the auto-generated
;     code produced by compiling 'OS_BIOS.rmg'
;------------------------------------------------

.= 0x16b0

os_print_float:
   push r0     ; Save registers
   push r1
   push r2
   push r3
   push r4
   push idx
   push lr     ; Auto-generated code
   push fp
   push r0
   movsp fp
   clr r0
   push r0
   clr r0
   push r0
   clr r0
   push r0
   clr r0
   push r0
   clr r0
   push r0
   clr r0
   push r0
   ldi idx,1
   ldx r0,[fp,idx]
   ldi idx,-5
   stx r0,[fp,idx]
   ldi idx,1
   ldx r0,[fp,idx]
   push r0
   ldi r0,32256
   push r0
   pop r1
   pop r0
   ldi r2,1
   cmp r0,r1
   jeq cond_None_121
   clr r2
cond_None_121:
   mov r2,r0
   push r0
   ldi idx,1
   ldx r0,[fp,idx]
   push r0
   ldi r0,65024
   push r0
   pop r1
   pop r0
   ldi r2,1
   cmp r0,r1
   jeq cond_None_122
   clr r2
cond_None_122:
   mov r2,r0
   push r0
   pop r1
   pop r0
   ldi r2,1
   clr r3
   cmp r0,r3
   jgt cond_os_print_float_123
   cmp r1,r3
   jgt cond_os_print_float_123
   clr r2
cond_os_print_float_123:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq if_os_print_float_119
   ldi r0,78
   call os_print_char
   ldi r0,97
   call os_print_char
   ldi r0,78
   call os_print_char
   clr r0
   jmp ret_os_print_float
if_os_print_float_119:
   ldi idx,1
   ldx r0,[fp,idx]
   push r0
   ldi r0,31744
   push r0
   pop r1
   pop r0
   ldi r2,1
   cmp r0,r1
   jeq cond_None_126
   clr r2
cond_None_126:
   mov r2,r0
   push r0
   ldi idx,1
   ldx r0,[fp,idx]
   push r0
   ldi r0,64512
   push r0
   pop r1
   pop r0
   ldi r2,1
   cmp r0,r1
   jeq cond_None_127
   clr r2
cond_None_127:
   mov r2,r0
   push r0
   pop r1
   pop r0
   ldi r2,1
   clr r3
   cmp r0,r3
   jgt cond_os_print_float_128
   cmp r1,r3
   jgt cond_os_print_float_128
   clr r2
cond_os_print_float_128:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq if_os_print_float_124
   ldi idx,1
   ldx r0,[fp,idx]
   push r0
   ldi r0,31744
   push r0
   pop r1
   pop r0
   ldi r2,1
   cmp r0,r1
   jeq cond_os_print_float_131
   clr r2
cond_os_print_float_131:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq if_os_print_float_129
   ldi r0,43
   call os_print_char
   jmp if_os_print_float_130
if_os_print_float_129:
   ldi r0,45
   call os_print_char
if_os_print_float_130:
   ldi r0,73
   call os_print_char
   ldi r0,110
   call os_print_char
   ldi r0,102
   call os_print_char
   clr r0
   jmp ret_os_print_float
if_os_print_float_124:
   ldi idx,1
   ldx r0,[fp,idx]
   push r0
   ldi r0,0
   push r0
   pop r1
   pop r0
   ldi r2,1
   cmp r0,r1
   jeq cond_None_134
   clr r2
cond_None_134:
   mov r2,r0
   push r0
   ldi idx,1
   ldx r0,[fp,idx]
   push r0
   ldi r0,32768
   push r0
   pop r1
   pop r0
   ldi r2,1
   cmp r0,r1
   jeq cond_None_135
   clr r2
cond_None_135:
   mov r2,r0
   push r0
   pop r1
   pop r0
   ldi r2,1
   clr r3
   cmp r0,r3
   jgt cond_os_print_float_136
   cmp r1,r3
   jgt cond_os_print_float_136
   clr r2
cond_os_print_float_136:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq if_os_print_float_132
   ldi r0,48
   call os_print_char
   ldi r0,46
   call os_print_char
   ldi r0,48
   call os_print_char
   clr r0
   jmp ret_os_print_float
if_os_print_float_132:
   ldi idx,1
   ldx r0,[fp,idx]
   push r0
   ldi r0,0
   push r0
   pop r1
   pop r0
   ldi r2,1
   xor r0,r1,r3
   ldi r4,0x8000
   and r3,r4,r3
   jnz cond_os_print_float_139_2
   and r0,r4,r3
   jz cond_os_print_float_139_2
   ldi r4,0x7fff
   and r0,r4,r3
   and r1,r4,r0
   mov r3,r1
cond_os_print_float_139_2:
   cmp r1,r0
   jgt cond_os_print_float_139
   clr r2
cond_os_print_float_139:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq if_os_print_float_137
   ldi r0,45
   call os_print_char
   ldi idx,1
   ldx r0,[fp,idx]
   push r0
   ldi r0,15360
   ldi r1,0x8000
   or r0,r1,r0
   push r0
   pop r1
   pop r0
   fmul r0,r1,r0
   push r0
   pop r0
   ldi idx,1
   stx r0,[fp,idx]
if_os_print_float_137:
while_os_print_float_141:
   ldi idx,1
   ldx r0,[fp,idx]
   push r0
   ldi r0,15360
   push r0
   pop r1
   pop r0
   ldi r2,1
   xor r0,r1,r3
   ldi r4,0x8000
   and r3,r4,r3
   jnz cond_os_print_float_143_2
   and r0,r4,r3
   jz cond_os_print_float_143_2
   ldi r4,0x7fff
   and r0,r4,r3
   and r1,r4,r0
   mov r3,r1
cond_os_print_float_143_2:
   cmp r1,r0
   jgt cond_os_print_float_143
   clr r2
cond_os_print_float_143:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq while_os_print_float_142
   ldi idx,-4
   ldx r0,[fp,idx]
   push r0
   ldi r0,1
   push r0
   pop r1
   pop r0
   sub r0,r1,r0
   push r0
   pop r0
   ldi idx,-4
   stx r0,[fp,idx]
   ldi idx,1
   ldx r0,[fp,idx]
   push r0
   ldi r0,18688
   push r0
   pop r1
   pop r0
   fmul r0,r1,r0
   push r0
   pop r0
   ldi idx,1
   stx r0,[fp,idx]
   jmp while_os_print_float_141
while_os_print_float_142:
while_os_print_float_145:
   ldi idx,1
   ldx r0,[fp,idx]
   push r0
   ldi r0,18688
   push r0
   pop r1
   pop r0
   ldi r2,1
   xor r0,r1,r3
   ldi r4,0x8000
   and r3,r4,r3
   jnz cond_os_print_float_147_2
   and r0,r4,r3
   jz cond_os_print_float_147_2
   ldi r4,0x7fff
   and r0,r4,r3
   and r1,r4,r0
   mov r3,r1
cond_os_print_float_147_2:
   cmp r0,r1
   jge cond_os_print_float_147
   clr r2
cond_os_print_float_147:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq while_os_print_float_146
   ldi idx,-4
   ldx r0,[fp,idx]
   push r0
   ldi r0,1
   push r0
   pop r1
   pop r0
   add r0,r1,r0
   push r0
   pop r0
   ldi idx,-4
   stx r0,[fp,idx]
   ldi idx,1
   ldx r0,[fp,idx]
   push r0
   ldi r0,18688
   push r0
   pop r1
   pop r0
   fdiv r0,r1,r0
   push r0
   pop r0
   ldi idx,1
   stx r0,[fp,idx]
   jmp while_os_print_float_145
while_os_print_float_146:
   ldi idx,-4
   ldx r0,[fp,idx]
   push r0
   ldi r0,3
   not r0,r0
   inc r0
   push r0
   pop r1
   pop r0
   ldi r2,1
   cmp r1,r0
   jgt cond_None_151
   clr r2
cond_None_151:
   mov r2,r0
   push r0
   ldi idx,-4
   ldx r0,[fp,idx]
   push r0
   ldi r0,3
   push r0
   pop r1
   pop r0
   ldi r2,1
   cmp r0,r1
   jgt cond_None_153
   clr r2
cond_None_153:
   mov r2,r0
   push r0
   pop r1
   pop r0
   ldi r2,1
   clr r3
   cmp r0,r3
   jgt cond_os_print_float_155
   cmp r1,r3
   jgt cond_os_print_float_155
   clr r2
cond_os_print_float_155:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq if_os_print_float_149
   ldi idx,1
   ldx r0,[fp,idx]
   call print_flt_dig
   ldi idx,-3
   stx r0,[fp,idx]
   ldi r0,46
   call os_print_char
   ldi r0,0
   ldi idx,-2
   stx r0,[fp,idx]
for_os_print_float_156:
   ldi idx,-2
   ldx r0,[fp,idx]
   push r0
   ldi r0,3
   push r0
   pop r1
   pop r0
   ldi r2,1
   cmp r1,r0
   jgt cond_os_print_float_159
   clr r2
cond_os_print_float_159:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq for_os_print_float_158
   ldi r0,18688
   push r0
   ldi idx,1
   ldx r0,[fp,idx]
   push r0
   pop r1
   pop r0
   fmul r0,r1,r0
   push r0
   ldi idx,-3
   ldx r0,[fp,idx]
   push r0
   pop r1
   pop r0
   fsub r0,r1,r0
   push r0
   pop r0
   ldi idx,1
   stx r0,[fp,idx]
   ldi idx,1
   ldx r0,[fp,idx]
   call print_flt_dig
   ldi idx,-3
   stx r0,[fp,idx]
for_os_print_float_157:
   ldi idx,-2
   ldx r0,[fp,idx]
   push r0
   ldi r0,1
   push r0
   pop r1
   pop r0
   add r0,r1,r0
   push r0
   pop r0
   ldi idx,-2
   stx r0,[fp,idx]
   jmp for_os_print_float_156
for_os_print_float_158:
   ldi idx,-4
   ldx r0,[fp,idx]
   push r0
   ldi r0,0
   push r0
   pop r1
   pop r0
   clr r2
   cmp r0,r1
   jeq cond_os_print_float_163
   inc r2
cond_os_print_float_163:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq if_os_print_float_161
   ldi r0,101
   call os_print_char
   ldi idx,-4
   ldx r0,[fp,idx]
   call os_print_int
if_os_print_float_161:
   jmp if_os_print_float_150
if_os_print_float_149:
   ldi idx,-4
   ldx r0,[fp,idx]
   push r0
   ldi r0,0
   push r0
   pop r1
   pop r0
   ldi r2,1
   cmp r0,r1
   jge cond_os_print_float_166
   clr r2
cond_os_print_float_166:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq if_os_print_float_164
   ldi idx,-4
   ldx r0,[fp,idx]
   push r0
   ldi r0,0
   push r0
   pop r1
   pop r0
   ldi r2,1
   cmp r0,r1
   jeq cond_os_print_float_170
   clr r2
cond_os_print_float_170:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq if_os_print_float_168
   ldi r0,5
   ldi idx,0
   stx r0,[fp,idx]
   ldi r0,1
   ldi idx,-1
   stx r0,[fp,idx]
   jmp if_os_print_float_169
if_os_print_float_168:
   ldi idx,-4
   ldx r0,[fp,idx]
   push r0
   ldi r0,4
   push r0
   pop r1
   pop r0
   add r0,r1,r0
   push r0
   pop r0
   ldi idx,0
   stx r0,[fp,idx]
   ldi idx,0
   ldx r0,[fp,idx]
   push r0
   ldi r0,3
   push r0
   pop r1
   pop r0
   sub r0,r1,r0
   push r0
   pop r0
   ldi idx,-1
   stx r0,[fp,idx]
if_os_print_float_169:
   ldi r0,0
   ldi idx,-2
   stx r0,[fp,idx]
for_os_print_float_171:
   ldi idx,-2
   ldx r0,[fp,idx]
   push r0
   ldi idx,0
   ldx r0,[fp,idx]
   push r0
   pop r1
   pop r0
   ldi r2,1
   cmp r1,r0
   jgt cond_os_print_float_174
   clr r2
cond_os_print_float_174:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq for_os_print_float_173
   ldi idx,-2
   ldx r0,[fp,idx]
   push r0
   ldi idx,-1
   ldx r0,[fp,idx]
   push r0
   pop r1
   pop r0
   ldi r2,1
   cmp r0,r1
   jeq cond_os_print_float_178
   clr r2
cond_os_print_float_178:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq if_os_print_float_176
   ldi r0,46
   call os_print_char
   jmp for_os_print_float_172
if_os_print_float_176:
   ldi idx,1
   ldx r0,[fp,idx]
   call print_flt_dig
   ldi idx,-3
   stx r0,[fp,idx]
   ldi r0,18688
   push r0
   ldi idx,1
   ldx r0,[fp,idx]
   push r0
   pop r1
   pop r0
   fmul r0,r1,r0
   push r0
   ldi idx,-3
   ldx r0,[fp,idx]
   push r0
   pop r1
   pop r0
   fsub r0,r1,r0
   push r0
   pop r0
   ldi idx,1
   stx r0,[fp,idx]
for_os_print_float_172:
   ldi idx,-2
   ldx r0,[fp,idx]
   push r0
   ldi r0,1
   push r0
   pop r1
   pop r0
   add r0,r1,r0
   push r0
   pop r0
   ldi idx,-2
   stx r0,[fp,idx]
   jmp for_os_print_float_171
for_os_print_float_173:
   jmp if_os_print_float_165
if_os_print_float_164:
   ldi r0,48
   call os_print_char
   ldi r0,46
   call os_print_char
   ldi r0,1
   not r0,r0
   inc r0
   push r0
   pop r0
   ldi idx,-2
   stx r0,[fp,idx]
for_os_print_float_179:
   ldi idx,-2
   ldx r0,[fp,idx]
   push r0
   ldi idx,-4
   ldx r0,[fp,idx]
   push r0
   pop r1
   pop r0
   ldi r2,1
   cmp r0,r1
   jgt cond_os_print_float_182
   clr r2
cond_os_print_float_182:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq for_os_print_float_181
   ldi r0,48
   call os_print_char
for_os_print_float_180:
   ldi idx,-2
   ldx r0,[fp,idx]
   push r0
   ldi r0,1
   push r0
   pop r1
   pop r0
   sub r0,r1,r0
   push r0
   pop r0
   ldi idx,-2
   stx r0,[fp,idx]
   jmp for_os_print_float_179
for_os_print_float_181:
   ldi r0,0
   ldi idx,-2
   stx r0,[fp,idx]
for_os_print_float_184:
   ldi idx,-2
   ldx r0,[fp,idx]
   push r0
   ldi r0,4
   push r0
   pop r1
   pop r0
   ldi r2,1
   cmp r1,r0
   jgt cond_os_print_float_187
   clr r2
cond_os_print_float_187:
   mov r2,r0
   push r0
   pop r0
   clr r1
   cmp r0,r1
   jeq for_os_print_float_186
   ldi idx,1
   ldx r0,[fp,idx]
   call print_flt_dig
   ldi idx,-3
   stx r0,[fp,idx]
   ldi r0,18688
   push r0
   ldi idx,1
   ldx r0,[fp,idx]
   push r0
   pop r1
   pop r0
   fmul r0,r1,r0
   push r0
   ldi idx,-3
   ldx r0,[fp,idx]
   push r0
   pop r1
   pop r0
   fsub r0,r1,r0
   push r0
   pop r0
   ldi idx,1
   stx r0,[fp,idx]
for_os_print_float_185:
   ldi idx,-2
   ldx r0,[fp,idx]
   push r0
   ldi r0,1
   push r0
   pop r1
   pop r0
   add r0,r1,r0
   push r0
   pop r0
   ldi idx,-2
   stx r0,[fp,idx]
   jmp for_os_print_float_184
for_os_print_float_186:
if_os_print_float_165:
if_os_print_float_150:
ret_os_print_float:
   pop idx
   pop idx
   pop idx
   pop idx
   pop idx
   pop idx
   pop idx
   pop fp
   pop lr
   pop idx     ; Restore registers
   pop r4
   pop r3
   pop r2
   pop r1
   pop r0
   ret

;----------------------------------------------------------------
; BIOS - Terminate a program, and if the error code is non-zero:
;          Display an Error Code on OUT_1
;          Turn on the ERR LED
;
; Location: ROM addr 0x1a90
;
; Input - R0 = Error Code
;----------------------------------------------------------------

.= 0x1a90

os_exit:
   clr r1               ; Error Code = 0 ?
   cmp r0,r1
   jne disp_err
   end                  ; No error - Just stop the program

disp_err:
   mov r0,r1            ; Display the Error Code
   ldi r0,OUT_1
   call os_disp_out
   ldi r0,1             ; Turn the ERR LED on
   ldi r1,ERR
   st r0,[r1]
   end                  ; Stop the program

